### ISSUE TITLE
Duda asembly básico clases

### ISSUE THREAD

**Issue by jalliende** [IIC2343/syllabus-2021-1#10]
Hola, tengo una duda con respecto a la materia de mañana de la I1. En particular con el direccionamiento indirecto. Entiendo que si uno hace por ejemplo 
MOV A,(B)
se pone lo que exista en el espacio de memoria guardado en el registro B en el registro A, es decir, 
A= Mem[B],
pero mi duda es cómo puedo yo puedo guardar un espacio de memoria en B? A través de los literales? y de eso se encargaría el compilador o no?
y otra duda, en una I pasada que hacían:
ADD A, var1
y lo que dicen que se interpreta como  A = A + var1, pero mi duda es que var1 es una dirección de memoria o no?  ¿Cómo se interpretaría el nuevo valor de A? ¿Es una nueva posición dentro de la memoria?
Muchas gracias de antemano.

**Comment by tocococa** [comment]
Hola!

La instrucción MOV A, (B), como tu dices, necesita que en B haya una dirección de memoria para cargar su contenido en A y eso lo puedes hacer con una instrucción del estilo MOV B, label, donde label sería la dirección en memoria que estás cargando.

En el caso de ADD A, var1, var1 en realidad es algo así como 0x10010060, que es una dirección de memoria, y al hacer ADD A, var1, lo que se almacena en A es la dirección 0x10010060 + el valor de A. Por ejemplo, si var1 fuera la dirección de inicio de un arreglo, podrías hacer MOV A, 4 -> ADD A, var1, para acceder al cuarto elemento del arreglo que parte en var1.

**Comment by jalliende** [comment]
otra duda pequeña.
Si hago:
MOV (0), A
estoy haciendo
Mem[0] = A o no?

**Comment by tocococa** [comment]
Claro, en esa instrucción estás almacenando lo que sea que había en A en la dirección de memoria 0, aunque normalmente usarías un label en lugar de un literal para referenciar la memoria. En los apuntes del curso, en el capítulo 2 - Programabilidad, en la página 18, están casi todas las instrucciones del computador básico sin saltos, por si quieres revisar que instrucciones hay y que hace cada una.
