### ISSUE TITLE
Q&A I1

### ISSUE THREAD

**Issue by tocococa** [IIC2343/syllabus-2021-1#11]
# Recuerden entregar antes de las 21:59 ‼

# Formato

Puede ser Latex? 
**R:** Si, y se ganan nuestro corazón.

Puede ser a mano? 
**R:** Si, pero que se entienda, con letra clara.

Entreguen UN .pdf por cuestionario en SIDING de acuerdo a la pregunta que corresponde.

# P0

Se puede firmar digitalmente? 
**R:**  Sí, lo que nos importa es que esté firmado por ustedes

Dónde se entrega? 
**R:** Junto a la pregunta 1 en ese buzón.

# P1

## P1.a

Cuando se pregunta por los problemas que surgen, a que se refieren? 
**R:** Se refiere a los tres problemas mencionados en las diapositivas de clases, que tienen signo y magnitud, además de mencionar como estos problemas se resuelven con complemento de 2 y porque esta notación facilita el hardware.

En la 1a hay que explicar los 3 puntos mencionados en clase solamente o además agregar otras ventajas?
**R:** No es necesario, solo deben considerar cada uno de los problemas descritos en clase y como complemento a 2 los minimiza o elimina a nivel de hardware.

## P1.b

Se debe hacer una demostración, no basta con dar un ejemplo. Lo relevante es demostrar que la extensión de bits preserva el valor del número original para cualquier número n.

# P2

En la tabla de instrucciones, para las instrucciones `MOV A, Lit` y `MOV B, Lit` debiesen tener la señal de control `Sa0` en `1` y no en `0`.  La tabla correcta está en la página 18 del archivo en Apuntes > Capitulo 2 > 4 -  Programabilidad.

Hay un diagrama en drawio del computador básico en la carpeta Material Complementario, que les podría ayudar a escribir sus respuestas.

El registro C también es de 8 bits?
**R:** Sí, es idénticos a los registros A y B.
## P2.a

Puedo agregar un cable de control?
**R:** Sí, pueden agregar todos los elementos que quieran, lo único que **no pueden cambiar es la ALU**.

Si estamos agregando un nuevo registro, no deberíamos tener tres inputs en la ALU?
**R:** No, es parte de la pregunta que ustedes decidan cómo se redirigen los contenidos de cada uno de los registros al input correspondiente en la ALU.

Puedo conectar el resultado de la ALU al registro C?
**R:** Sí, pero esto se debe hacer de forma que no interfiera con el funcionamiento normal de la ALU.

El registro de C puede ser ingresado a través de algún input como B o debe ser algo obtenido a partir de ALU como A?
**R:** El registro C va junto a A y a B, cómo haces que la ALU de dos entradas y una salida pueda operar con dicho registro es parte de la pregunta.

## P2.b

Debemos agregar las instrucciones en el orden que ya hay?
**R:** No, basta con que las agreguen al final.

Si agregamos señales, debemos reescribir también las instrucciones anteriores?
**R:** No, basta con que describan las instrucciones nuevas y lo que se pide para cada una.

Tenemos que agregar ADD A,C y MOV C,B a los opcodes y nada mas para la 2b?
**R:** Si, y además explicar como quedan los bits que corresponden a sus señales de control.

# P3

El status de Z y N depende de una resta? 
**R:** No, depende exclusivamente del resultado de una operación cualquiera que haya realizado la ALU.

De que input depende cada circuito que dibujemos?
**R:** Depende exclusivamente del resultado de la ALU.

Que componentes podemos usar?
**R:** Se debiesen poder hacer todos los circuitos utilizando solo las compuertas básicas vistas en clase, pero también pueden usar otros componentes compuestos que se hayan visto, como multiplexores o decoders.

Puedo usar los resultados de Z o N para hacer algo con P, T o E?
**R:** Sí.

En P3, debo hacer las compuertas lógicas de a 2 bits, o puedo hacerlo con más de dos por simplicidad del dibujo?
**R:**  Puedes simplificar, por ejemplo, un AND con más de dos inputs, pero componentes más grandes que no se hayan visto en clases tienes que dibujarlos. Si es algo medio extraño, por favor aclaren con una tabla de verdad o una descripción de que hace el componente.

Podemos asumir que los números del resultado de la ALU están en complemento de 2?
**R:** Sí, el computador básico funciona en complemento de 2.

## P3.a

En la 3.a no es necesario modificar la ALU?
**R:** No, lo que deben hacer es diseñar un circuito que genera los valores de Z y N dependiendo del resultado de la ALU.

Debemos dibujar los 8 cables para cada bit?
**R:** No es necesario, pueden usar la notación para un bus de datos de 8 bits y si necesitan sacar un cable en particular, dejen claro de que bit se trata y es suficiente.

Puedo usar un numero extra, por ejemplo 0, como input?
**R:** Si, pero justifiquen sus decisiones respecto al diseño del circuito.

## P3.c

Cuando dice que el resultado sea una potencia de 2, esto no incluye a los negativos?
**R:** No, un negativo no puede ser una potencia de 2, por lo que no se consideran esos resultado, deben fijarse que se trate de un positivo.

Necesito tener Z y N funcionando correctamente de las preguntas anteriores para responder esta pregunta?
**R:** No, puedes asumir que el resultado de tus preguntas anteriores es correcto.

## P3.d

Se considera al 0 como par? Es decir, si el número está formado por puros unos, ¿E debería valer 0 ó 1?
**R:** Si en la palabra no hay 0s, E debiese ser 0 ya que no se cumple la condición, o podría ser 1, ya que 0 es un par. Deben justificar su decisión y hacer el circuito acorde.

Con cantidad de 0, se refieren a bits en 0 a a los 0 en su representación decimal?
**R:** Nos referimos a la cantidad de bits en 0, incluyendo a los que se encuentran a la izquierda del último 1.

# P4

Que debemos responder?
**R:** Deben recorrer el programa, con el input que corresponda a ustedes, describir que es lo que hace el programa y, al finalizar, indicar que hay almacenado en cada registro y en cada celda de memoria que haya sido modificada.

Debemos ejecutar todas las instrucciones hasta llegar al end?
**R:** Así es, debiese ser un número finito de instrucciones.

La instrucción `SHR`, es un shift lógico o aritmético?
**R:** Es el shift soportador por el computador básico.

Que puedo almacenar en una dirección de memoria?
**R:** Puedes almacenar un byte completo.

A que computador se refiere con el computador de la pregunta 3?
**R:** Nos referimos al computador básico que aparece en el diagrama, antes de ser modificado por ustedes.

Con que valor parten los registros?
**R:** No puedes asumir ningún valor, estos parten con ruido.

**Comment by tocococa** [comment]
Hola @Aloncarrasco!
En cada buzón tienes que entregar un sólo archivo pdf con tus respuestas.

**Comment by srhernandez1** [comment]
En P3, debo hacer las compuertas lógicas de a 2 bits, o puedo hacerlo con más de dos por simplicidad del dibujo?
Por ejemplo, si tengo que usar una compuerta con los 8 bits, debo hacer 7 compuertas, o puedo hacer 1 en la que entren los 8 bits?

**Comment by maogaz** [comment]
En la P2, el registro de C puede ser ingresado a través de algún input como B o debe ser algo obtenido a partir de ALU como A?

**Comment by mpbosnic** [comment]
Hola! En la P3)d) se considera al 0 como par? Es decir, si el número está formado por puros unos, ¿E debería valer 0 ó 1?

**Comment by tocococa** [comment]
@srhernandez1, puedes simplificar, por ejemplo, un AND con más de dos inputs, pero componentes más grandes que no se hayan visto en clases tienes que dibujarlos.

**Comment by jorge-schenke** [comment]
Hola! creo que la pregunta 2.a) está mal redactada:
Dice "Explica de manera clara algunas de las ventajas en cuanto a hardware del complemento de 2" hasta ahí todo bien.
Después dice "Considera cada uno de los tres problemas que mencionamos en clases para ESTA ÚLTIMA represetnación.
Osea que tenemos que indicar 3 problemas de la representación con complemento de 2? eso entiendo yo por lo menos.

**Comment by AlonsoDS** [comment]
Los que no podemos entregar por SIDING, sino por correo, también separamos un archivo por pregunta (o sea, mandamos 4 archivos en total)?

**Comment by cchauriye** [comment]
Hola! En la pregunta 3 podemos usar alguna herramienta online (como esta https://logic.ly/demo/) para dibujar los circuitos?

**Comment by sufigueroa** [comment]
Sii!! La idea es que no le arme el circuito solo, pero para dibujar y simularlo si se puede.  Suerte!!

**Comment by sufigueroa** [comment]
@jorge-schenke las desventajas se refiere a la representacion de signo- magnitud, no a la de complemento 2.

**Comment by lgolborne** [comment]
> Los que no podemos entregar por SIDING, sino por correo, también separamos un archivo por pregunta (o sea, mandamos 4 archivos en total)?

@AlonsoDS  Si, es mejor que los separen para facilitar la corrección

**Comment by frduran** [comment]
Creo que lo preguntaron en las sesiones de consulta pero para asegurarme...
En la pregunta 3, se debe ir modificando constantemente el diagrama de la respuesta anterior o puedo hacer un nuevo diagrama para lo que se pregunta en sí?

**Comment by sufigueroa** [comment]
> a al 0 como par? Es decir, si el número está formado por puros unos

Eso se deja a tu criterio, pero el que decidas tienes que dejarlo escrito.

**Comment by sufigueroa** [comment]
> e debe ir modificando constantemente el diagrama

Sii! puedes dejarlo como un diagrama independiente.

**Comment by lgolborne** [comment]
> > a al 0 como par? Es decir, si el número está formado por puros unos
> 
> Eso se deja a tu criterio, pero el que decidas tienes que dejarlo escrito.

Pro tip: el 0 es par ajajaas (es mas facil la implementacion)

**Comment by nucontreras** [comment]
Hola! En la P4 hay un MOV (B), A. Ese (B) hace referencia al registro B o a una variable B?

**Comment by FJavierOss** [comment]
Hola, existe algún nombre especifico en el que se tenga que subir cada pregunta al cuestionario del siding? Ejemplo P1_nombreapellido.pdf ?

**Comment by lgolborne** [comment]
> Hola! En la P4 hay un MOV (B), A. Ese (B) hace referencia al registro B o a una variable B?

En la clase de procesador III esta la ISA completa del computador básico. En especifico también esta esa instrucción y lo que hace

**Comment by lgolborne** [comment]
> Hola, existe algún nombre especifico en el que se tenga que subir cada pregunta al cuestionario del siding? Ejemplo P1_nombreapellido.pdf ?

@FJavierOss Da lo mismo el nombre del archivo, P1.pdf esta bien

**Comment by humbertoortuzar** [comment]
Para la pregunta 3, podemos usar un elemento como un full adder o tendríamos que expresarlo en sus compuertas básicas?

**Comment by raimundoloeser** [comment]
Se pueden ocupar operadores logicos de mas de 2 inputs?

**Comment by lgolborne** [comment]
> Para la pregunta 3, podemos usar un elemento como un full adder o tendríamos que expresarlo en sus compuertas básicas?

@humbertoortuzar Si, pueden usar un full adder

**Comment by sufigueroa** [comment]
> Se pueden ocupar operadores logicos de mas de 2 inputs?

Si se puede. Suerte!

**Comment by lgolborne** [comment]
> Se pueden ocupar operadores logicos de mas de 2 inputs?

@raimundoloeser si se puede usar AND y OR de varias entradas

**Comment by MINGOD24** [comment]
Para la pregunta 3, puedo utilizar un XOR con más de dos inputs?

**Comment by lgolborne** [comment]
> Para la pregunta 3, puedo utilizar un XOR con más de dos inputs?

Si, pero especifica como se comporta ya que no es tan intuitivo como el AND y OR

**Comment by Aloncarrasco** [comment]
Para la 4 estoy en un computador de 8 bits? (podría tener overflows por ejemplo?)

**Comment by diegovaras97** [comment]
Hola, para la 3d consideramos el bus de 8 bits completo o sólo los 7 bits que no son signos?

**Comment by lgolborne** [comment]
> Para la 4 estoy en un computador de 8 bits? (podría tener overflows por ejemplo?)

@Aloncarrasco Si, es el computador basico del curso asi que es de 8 bits y podria haber overflow

**Comment by lgolborne** [comment]
> Hola, para la 3d consideramos el bus de 8 bits completo o sólo los 7 bits que no son signos?

@diegovaras97 el bus completo

**Comment by spplaza** [comment]
> > Hola! En la P4 hay un MOV (B), A. Ese (B) hace referencia al registro B o a una variable B?
> 
> @nucontreras En la clase de procesador III esta la ISA completa del computador básico. En especifico también esta esa instrucción y lo que hace

No entiendo si MOV (B), A es lo mismo que MOV B, A

**Comment by FJavierOss** [comment]
Para la pregunta 3 c), Es 2^0 es considerado potencia de 2? O se considera a partir de 2^1 en adelante?

**Comment by faguilerag** [comment]
> > Hola! En la P4 hay un MOV (B), A. Ese (B) hace referencia al registro B o a una variable B?
> 
> @nucontreras En la clase de procesador III esta la ISA completa del computador básico. En especifico también esta esa instrucción y lo que hace

Sigo teniendo dudas respecto a lo que hace, no me queda claro con la tabla :(

**Comment by lgolborne** [comment]
> > > Hola! En la P4 hay un MOV (B), A. Ese (B) hace referencia al registro B o a una variable B?
> > 
> > 
> > @nucontreras En la clase de procesador III esta la ISA completa del computador básico. En especifico también esta esa instrucción y lo que hace
> 
> No entiendo si MOV (B), A es lo mismo que MOV B, A

@faguilerag @spplaza Revisen el set de instrucciones completo (quizas les sirve tambien la microaquitectura), no les puedo decir mucho mas que eso. Quizas les sirve pensar es lo mismo MOV A,var que MOV A,(var)? si no, cual es la diferencia?

**Comment by lgolborne** [comment]
> Para la pregunta 3 c), Es 2^0 es considerado potencia de 2? O se considera a partir de 2^1 en adelante?

Si a lo primero

**Comment by VicenteGM123** [comment]
Hola! sería posible que explicitarán el funcionamiento de los shift?

**Comment by lgolborne** [comment]
> Hola! sería posible que explicitarán el funcionamiento de los shift en la pregunta 4?


Lamentablemente no, la idea de la pregunta es que entiendan el funcionamiento y secuencia de cada instrucction. Te recomiendo revisar el material de clases y ayudantias. Suerte con lo que queda!

**Comment by maogaz** [comment]
Alguna sugerencia para entender el shift? he buscado en las clases y ayudantías y no logro encontrar nada explicito

**Comment by lgolborne** [comment]
> Alguna sugerencia para entender el shift? he buscado en las clases y ayudantías y no logro encontrar nada explicito

@maogaz Lo lamento, pero la instancia para resolver este tipo de dudas no es la interrogacion. Revisa bien y de seguro encuentras algo

**Comment by pita-horn** [comment]
**P4**
Hola! Me entró la duda si en la P4 tenemos que poner los cambios de valores para cada iteracion del loop :O ?
Es decir, si yo calculo que son X iteraciones, debo registrar esos X cambios de cada linea del codigo loop?

**Comment by lgolborne** [comment]
> **P4**
> Hola! Me entró la duda si en la P4 tenemos que poner los cambios de valores para cada iteracion del loop :O ?
> Es decir, si yo calculo que son X iteraciones, debo registrar esos X cambios de cada linea del codigo loop?
> Puedo poner los cambios para la primera iteración y luego explicar los cambios importantes solamente para el resto?

@pita-horn Hola, la idea es que detallen la ejecución completa, es decir cada instrucción en cada iteración. Si no alcanzas por tiempo obvio que es mejor que expliques que pasa después para la corrección. Mucha suerte!
