### ISSUE TITLE
Posibilidad de dar tiempo adicional

### ISSUE THREAD

**Issue by tatanpoker09** [IIC2343/syllabus-2021-1#12]
Hola, 
Debido a la longitud de la prueba, como por ejemplo la posible longitud de la pregunta 4 para algunos compañeros. Además de que hubo personas que también tuvieron clases el día de hoy, existe la posibilidad de dar un tiempo adicional en la prueba? (quizás hasta las 23:59).

Muchas gracias por considerarlo,
Christian Eilers

**Comment by Luckbox314** [comment]
La verdad estaría bien necesario 🤝

**Comment by tocococa** [comment]
Hola! Dimos media hora más de plazo, publiqué un aviso en SIDING pero parece que el mail no se mandó, pero los formularios quedaron para las 22:30.
