### ISSUE TITLE
RISC-V sintaxis para comparaciones

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2343/syllabus-2021-1#13]
Hola en clases usamos el CMP para comparar cosas. Como es es comando en Risc-V?

Y otra cosa que no me queda clara, podemos usar el registro a2 para hacer lo que queramos o solo para hacer cosas de argumentos a funciones como dice el greencard?
y similarmente, puedo usar el registro 1 como yo quiera o también tiene que ser para valores de retorno?

**Comment by lgolborne** [comment]
Hola, para hacer saltos condicionales en RISC-V no es necesario hacer CMP si no que se usa directamente un branch (beq, bneq, blt, por ejemplo).

Con respecto a los registros es mejor que uses del a2 en adelante o t3 en adelante o s2 en adelante. Esto por que otros estan reservados para otras cosas como por ejemplo a0 y a1 para valores de retornos o sp para stack pointer.
