### ISSUE TITLE
[T1] Duda Enunciado

### ISSUE THREAD

**Issue by fivaldivia** [IIC2343/syllabus-2021-1#14]
Hola, estoy teniendo un problema en donde busqué un ejemplo de matriz invertible en internet para usar de ejemplo pero no se me cumple lo que sale en enunciado para que sea invertible. Aquí dejo mi ejemplo, según lo que entendí:
![WhatsApp Image 2021-04-25 at 14 08 48](https://user-images.githubusercontent.com/42453679/116004306-22c44200-a5d0-11eb-8579-dea5d1cfd459.jpeg)
No se si no entendí bien el enunciado, pero al comparar el valor de la diagonal en ningún caso me da mayor a la suma de los otros. Gracias!

**Comment by lgolborne** [comment]
Hola, lo que se plantea en el enunciado es que si una matriz tiene diagonal estrictamente dominante, entonces esta es invertible. Ojo que no es lo mismo que decir una matriz es invertible si y solo si su diagonal es dominante. De todas formas no les pedimos que se preocupes de si es invertible o no, si no mas bien de que revisen si se cumple la propiedad de la diagonal. Saludos y suerte en la tarea.
