### ISSUE TITLE
[T1] Execution terminated with errors

### ISSUE THREAD

**Issue by bgfeuereisen** [IIC2343/syllabus-2021-1#15]
Hola buenas,
Ejecuto mi código y me aparece lo siguiente:
![image](https://user-images.githubusercontent.com/53834466/116152607-229d7280-a6b4-11eb-88d6-45e7285f6554.png)
Si bien me aparece: Assemble: operation completed succesfully, más arriba me aparece Step: execution terminated with errors y no sé que clase de error puede ser eso.
¿Alguna sugerencia?
Gracias

**Comment by tocococa** [comment]
Hola! El error `Step: execution terminated with errors` te aparece una vez que corres el programa? De lo que alcanzo a leer que no esta cortado, el error está apareciendo porque estás tratando de acceder a una dirección de memoria que no existe o está reservada para alguna otra cosa que no es tu programa.

Te recomiendo que revises la ayudantía de RISC-V para que entiendas que es lo que hace RARS y porqué en primera instancia te dice que no hay errores al ejecutar el assembler, pero luego te muestra un error al ejecutar tu programa.

**Comment by bgfeuereisen** [comment]
Si, me aparece ese error una vez que corro el programa. Revisé paso por paso como iba avanzando mi código y parece estar todo en orden. Asimismo, revisé la ayudantía previamente, pero no logré nada, por eso la issue. 
En la foto se muestra todo lo que me aparece, o hay nada cortado.

**Comment by bgfeuereisen** [comment]
Ya lo resolví. Gracias

**Comment by tocococa** [comment]
Que bueno que lo resolviste!
