### ISSUE TITLE
[T1] Test case 

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2343/syllabus-2021-1#16]
Hola, nos podrían compartir los test case para probar la tarea? 😄

**Comment by tocococa** [comment]
Hola! No tenemos casos de prueba por ahora, pero si quieres puedes revisar [esta issue](https://github.com/IIC2343/syllabus-2021-1/issues/5) donde se explica un poco que casos deberían poder manejar. Eso si puedo publicar a tener al menos tres casos de prueba no antes porque el miércoles tengo que entregar 4 tareas (；´д｀）ゞ
