### ISSUE TITLE
[T1] Overflow en la suma

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2343/syllabus-2021-1#17]
Hola, reescribí esto entero jajajs
Primero, no me quedó claro si puede haber overflow en la suma de los valores de una fila. Se supone que la suma también se guarda en 8bits y el valor max antes del overflow es 127?
Si es que es así, existe alguna forma (con alguna etiqueta de risc V) de decirle a un registro que su valor tiene q estar en 8bits (si por ejemplo un registro tiene el valor 127, y se le suma 1 si se reescribe, que en vez de quedar como 128 quede como -128)?

**Comment by tocococa** [comment]
Hola, te recomiendo que leas [esta issue](https://github.com/IIC2343/syllabus-2021-1/issues/5) para ver el tema del overflow. Hasta donde yo se, no se puede cambiar el modo de operación de cada registro, por lo que esa "cota superior" la deberías implementar tú, si descubres que si se pueden usar etiquetas para eso, avísanos.

**Comment by sopadeoliva** [comment]
Oki, muchas gracias!
