### ISSUE TITLE
Duda registros a,s y t

### ISSUE THREAD

**Issue by jalliende** [IIC2343/syllabus-2021-1#18]
Vi el resto de issues pero no me quedo 100% claro. 
Entiendo que los registros **a** se utilizan para valores de retorno y argumentos de función.
Que los registros **t** se utilizan para elementos temporales
Lo que no entiendo bien es para que se utilizan los registros **s**, en la _green card_ dice que es para los _saved_ pero no entiendo a que se refiere con eso.
Y con respecto a la utilización de los registros en el enunciado dice: "además de respetar
las convenciones de llamada para los registros"
entonces en teoría no podemos ocupar los registros **a** a lo largo de la tarea a menos que llamemos a una función, me surgió la duda por que en https://github.com/IIC2343/syllabus-2021-1/issues/5#issuecomment-823343089 se respondió que da lo mismo cual utilizar.
Entonces, no se pueden ocupar los registros **a** a menos el *a0* para retornar a menos que llamemos a una función? O si se pueden utilizar y no será penalizado?
Y que hago por ejemplo en caso de necesitar (por ejemplo) de manera simultanea 10 registros? Tengo que buscar la manera de reducir esa cantidad, ya que solo existen 7 registros **t**?
Muchas gracias de antemano.

**Comment by tocococa** [comment]
Hola!

Los registros `s` se utilizan para aquellos valores que se deben preservar a través de llamadas a funciones/subrutinas, es decir, al cambiar a otra función, lo que estaba en los registros `s` (si se estaban usando) se debe respaldar a memoria.

En el caso de `a`, los puedes pensar como los registros que una función usa para recibir sus parámetros, trabajar con ellos y luego entregar lo que sea que es su resultado. Podrías pensar en el algoritmo que les pedimos que programen como una única función, por lo que puedes usar tanto `a` como `s` como `t` en medida que lo consideres necesario.

Por último, los registros `t` son simplemente para elementos temporales o auxiliares, como contadores, para almacenar un valor mientras se despeja otro registro, ect.

Dije lo que dije en la issue #5 porque en realidad lo importante no es que usen `a, t, s` al pie de la letra, si no que, por ningún motivo llamen a los registros a través de `x`, ya que hay instrucciones que, por ejemplo, usan `x1-3` para guardar automáticamente algunos valores, por lo que se les podría desordenar el programa. 

Si por algún motivo necesitas 10 registros a la vez, puedes aprovechar los demás registros para hacer lo que quieras, pero dudo que llegues a ese punto en esta tarea.

**Comment by jalliende** [comment]
Ya perfecto, preguntaba en verdad por que hice mi tarea ocupando principalmente los registros *a* entonces cambiarlos a registros *t* iba a ser un poco latero. 
Gracias!
