### ISSUE TITLE
Cuestionario en SIDING para T1

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2343/syllabus-2021-1#19]
Holaa! Estaba revisando el siding en la parte de cuestionarios para subir la T1 pero me sale que no existe. Solo me salen los 4 de la I1 del viernes pasado. ¿Todavía no está abierto? :0

**Comment by tocococa** [comment]
Hola!
Emmm, sep, todavía no está el cuestionario, pero creo que podría hacerlo ahora, gracias por recordármelo (>'-'<)
