### ISSUE TITLE
Clase 2, no hay grabación

### ISSUE THREAD

**Issue by maogaz** [IIC2343/syllabus-2021-1#2]
Hola, el link de la segunda clase no funciona:

![image](https://user-images.githubusercontent.com/26102280/113522536-37805d80-956f-11eb-931a-fae7e6e3a3b7.png)

**Comment by tocococa** [comment]
Hola! Eso pasa porque la nube de Zoom va borrando las grabaciones, espero tener lo antes posible un respaldo o algo similar andando.

**Comment by maogaz** [comment]
Si las empiezan a subir a YT o algo similar avisen pls 🙌 🙌

**Comment by tocococa** [comment]
Ya están los respaldos!
