### ISSUE TITLE
Fecha entrega tarea

### ISSUE THREAD

**Issue by Jprampad** [IIC2343/syllabus-2021-1#20]
Hola!

Quisiera saber la posibilidad de cambiar la fecha de la tarea 1. Si bien esta se entregó con mucha anterioridad, la semana de pruebas ha estado bastante pesada ya que todos los ramos concentran sus evaluaciones durante estas semanas, por la semana de receso. El lunes 3 de mayo, también es la prueba de EDD, el otro ramo que dicta el Profesor Yadran y varios de este curso están en ambos ramos, por lo que toparía, sumándole que también tenemos que entregar la tarea de EDD el jueves. Espero que puedan analizar la chance de mover uno o dos días la tarea para poder dedicarle el tiempo pertinente para poder aprender y desarrollar tranquilamente la tarea.

**Comment by lgolborne** [comment]
Supongo que les llego el aviso por siding pero te contesto por acá de todas formas. Se extendió el plazo de la T1 hasta el jueves 6 de Mayo. Éxito en todas sus tareas y evaluaciones!

**Comment by Jprampad** [comment]
Bueena! Muchas gracias, se pasaron!
