### ISSUE TITLE
Consulta sobre el parámetro N dado

### ISSUE THREAD

**Issue by fediaz3** [IIC2343/syllabus-2021-1#21]
Hoola, una consulta muy puntual

Si tengo una matriz de 3x3,
El tamaño de la matriz dado en la sección `.data`, es N=3 o N=9?

Gracias!

**Comment by tocococa** [comment]
Hola @fediaz3! 

Como se indica en el enunciado, el label `N:`, indica el largo o ancho de la matriz cuadrada, por lo que para una matriz de `mxm`, tendrías `N: m`

**Comment by fediaz3** [comment]
@tocococa gracias!

**Comment by mimunoz11** [comment]
Hola @tocococa  en el enunciado dicen que N es: "N es la dirección en memoria del byte que representa el tamaño de la matriz" luego señalan: "el tamaño máximo de la matriz es de 11 x 11." De esas 2 frases interpreté que el tamaño de una 11x11 es 121. ¿Puedo mantener mi programa con el supuesto de que N es 121? A mi parecer el enunciado estaba ambiguo y ya terminé la tarea por lo que esta aclaración implicaría realizar cambios.

**Comment by lgolborne** [comment]
Hola, no puedes dejar eso porque los tests se corrigen automaticamente y en el caso en el que tu programa tenga como entrada N = 3 no va a ejecutarse como es esperado

**Comment by mimunoz11** [comment]
Oka lo cambio entonces ajasjaj :c
