### ISSUE TITLE
Numero de 9 bits.

### ISSUE THREAD

**Issue by jtcaraball** [IIC2343/syllabus-2021-1#22]
Hola! En la tarea 1 se pide utilizar solo enteros de hasta 8 bits pero resulta muy lindo manejar overflow mediante una operación lógica entre el resultado de la suma y un número de 9 bits específico, esta permitido esto o debería buscar otra forma de solucionarlo? 

Saludos!! :D

**Comment by lgolborne** [comment]
Hola, la idea es simular el funcionamiento de un computador de 8 bits, por lo que no puedes utilizar el numero de 9 bits
