### ISSUE TITLE
[Tarea 1] Overflow

### ISSUE THREAD

**Issue by fivaldivia** [IIC2343/syllabus-2021-1#23]
Hola, me surgió una duda al momento de trabajar con overflow. Ya vi el video de ayuda, pero me quedó la duda de si puedo efectivamente cargar un valor que estaría produciendo overflow (mayor a 127 en mi caso) con el fin de luego hacer una comparación y efectivamente lidiar con este overflow? Es decir, que en algún registro aparezca un valor mayor a 127 es factible? A mi parecer si, ya que si efectivamente estuviera ocurriendo overflow habria un negativo por ejemplo, y a partir de ese valor yo decido que hacer con el overflow. Ojala me haya explicado, gracias!

**Comment by lgolborne** [comment]
Hola, la idea es simular el funcionamiento de un computador de 8 bits, por lo que no podrias guardar en un registro un numero mayor a 127 para hacer la comparacion. Aun asi, no deberias necesitarlo y se puede hacer sin superar el limite de 8 bis
