### ISSUE TITLE
Repositorio personal github

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2343/syllabus-2021-1#25]
Hola! Hace mucho tiempo acepté la invitación a mi repositorio personal para la tarea, pero borré el mail y no lo encuentro 😢   hay alguna forma de recuperarlo? Gracias!

**Comment by lgolborne** [comment]
Hola, en el curso no tenemos repositorios personales. Si tu duda es sobre la entrega de la tarea, debes realizarla en un buzon habilitado en el siding

**Comment by beatrizacuna** [comment]
Perdoon me confundí 😅   está duro el semestre
Muchas gracias! 😄
