### ISSUE TITLE
[Tarea 1] problema para testear overflow

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2343/syllabus-2021-1#26]
Estaba trabajando en mi tarea y me di cuenta de que los registros del emulador rars funcionan para valores mucho más grandes que 8 bits, entonces al sumar cosas mayores a 127 no se me produce overflow, hay alguna forma de configurar el rars para que los registros solo aguanten cosas de 8 bits? si no como debo simular los overflows?
lei otras issues pero me quedan dudas, yo no uso la data memory entonces no se me produciran overflows, esto se revisará a nivel de codigo por ejemplo?

**Comment by tocococa** [comment]
Hola @Aloncarrasco !

Como se menciona en la [issue 5](https://github.com/IIC2343/syllabus-2021-1/issues/4), en la [issue](https://github.com/IIC2343/syllabus-2021-1/issues/4), en la [issue 17](https://github.com/IIC2343/syllabus-2021-1/issues/17) y se comentó en la sesión de consultas de la tarea, el objetivo es que ustedes detecten cuando algún número que tienen almacenado en un registro deja de poder ser representado con 8 bits. Como se indica en el enunciado de la tarea, se revisará que manejen adecuadamente estas condiciones, ya sea en su código o durante la ejecución.
