### ISSUE TITLE
T1 - Dudas I/O

### ISSUE THREAD

**Issue by JoacoCoyu** [IIC2343/syllabus-2021-1#3]
Hola!

Me surgieron dos dudas entorno a los inputs y outputs esperados de la T1.

1- Una duda para clarificar: un ejemplo de input de matriz M que utilizarían para correr la tarea sería del tipo:
```
M: .byte 4, 2, -1, 2
```
Representando en forma de arreglo a la matriz [[4, 2], [-1, 2]] de tamaño 2? 

Y relacionado a esto, en nuestro código no debemos preocuparnos de la forma en que ustedes correrán las 6 matrices de prueba? Es decir, bastaría con dejar el inicio del código de la siguiente manera y ustedes introducirían los inputs?

```
# Matriz
	M: .byte 
	N: .byte
```

2- Mi segunda pregunta es en relación a la forma en que debemos escribir el output y tal vez un poco más técnica. Programando en el emulador `rars_0e138d8.jar`, para saber si la matriz tiene o no una diagonal estrictamente dominante, bastaría con que en la sección de la derecha (foto a continuación) del programa aparezca en el registro `a0` un "0x00000001" o "0x00000000" respectivamente? Es decir, no deberíamos utilizar ninguna instrucción del tipo store como para almacenar ese valor o hacer algo más?

![ess](https://user-images.githubusercontent.com/48266376/114968968-689d3f80-9e45-11eb-9644-4a98be3fe91c.png)

Muchas gracias!

**Comment by tocococa** [comment]
Hola!

Sobre tu primera pregunta, si, un input tipo
```
M: .byte 3,4,6,7
N: 2
``` 
representa la matriz [[3,4],[6,7]]. En su código necesitamos que usen `M` como label de inicio para la matriz y `N` como label del tamaño, pero pueden hacer una entrega con una matriz anotada o dejarla en blanco, da un poco lo mismo eso.

Sobre tu segunda pregunta, la idea es que termines con 0 en `a0` si no cumple la condición o 1 si la cumple. Rn el menú del dropdown "Settings" del emulador, está la opción para pasar a notación decimal en los registros, para que no te enredes con hexadecimal:
![image](https://user-images.githubusercontent.com/22779371/115088550-689d4e00-9ede-11eb-8de7-0a582dd08e61.png)

Efectivamente no es necesario que uses `sb` para pasar el resultado, basta con que dejes `a0` en el valor correcto, que es el registro que por convención se usa para guardar el retorno de una función.

**Comment by JoacoCoyu** [comment]
Hola!
Muchas gracias por la aclaración. Que tengas buena semana.
Saludos!
