### ISSUE TITLE
Formato entrega asm a txt

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2343/syllabus-2021-1#30]
Hola, termine la tarea y quedó guardada en mi computador con extensión asm.
Veo que en el enunciado dice que debe estar en txt. Esto lo hago simplemente haciendo copy/paste de lo que dice el archivo asm, lo pego en un block de notas y lo guardo (txt) ?? O hay otra forma

**Comment by tocococa** [comment]
Hola @dsepulveda3, basta con que cambies la extensión de `.asm` a `.txt`.
