### ISSUE TITLE
[Tarea 1] Duda cargar matriz

### ISSUE THREAD

**Issue by Gjescalante** [IIC2343/syllabus-2021-1#31]
Hola, quería saber si se puede cargar la matriz usando .word como vimos en la ayudantía, (porque en el enunciado sale de ejemplo que hay que cargarla como byte) gracias por su tiempo.

**Comment by tocococa** [comment]
Hola @Gjescalante !

Como dice en el enunciado, tienen que usar `.byte` para declarar el tamaño del entero a guardar en memoria. Si revisas las issues #5. #23 y #22 puedes ver un poco más porqué les estamos pidiendo esto.
