### ISSUE TITLE
[Tarea 1] Duda overflow

### ISSUE THREAD

**Issue by lucas-valenzuela** [IIC2343/syllabus-2021-1#32]
Hola,

ya tengo hecha la tarea pero me surgió una duda. Supongamos que los elementos no diagonales de una fila son [110, 60, -60] y el elemento diagonal es 120. Los elementos se van sumando en orden. El problema es que al agregar el segundo elemento a la suma da overflow, por lo que le digo al programa que se detenga y retorne 0. Sin embargo, es claro que la suma de los 3 elementos es 110 que es menor que la diagonal, por lo que el a0 debería retornar 1.

Mi duda es si es correcto parar el programa una vez que haya tenido overflow a pesar de que la suma total no da overflow. Si es incorrecto, encuentro dificil plantear una solución, debido a que pienso que se debería realizar algún tipo de ordenación previa a cada fila antes de aplicar la lógica (por ejemplo, intercalar al elemento mayor con el menor, y así sucesivamente).

**Comment by tocococa** [comment]
Hola @lucas-valenzuela !

Siguiendo con tu ejemplo, los elementos de esa fila en total suman 110+60+|-60|=230, ya que el algoritmo aplica valor absoluto a cada elemento de la sumatoria, por lo que si en cualquier combinación de valores de la suma ocurre overflow, puedes concluir el resultado de la evaluación de esa fila.

**Comment by lucas-valenzuela** [comment]
ahhhh que bobo, estaba aplicando valor absoluto a la suma total, no a cada elemento particular.
Gracias totococa
