### ISSUE TITLE
[Tarea1]Escribir en a0

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2343/syllabus-2021-1#34]
Hola!Tengo una duda, respecto a una parte del enunciado la que dice así,:

"En su programa, ustedes deberán revisar si es que una matriz M cumple con esta condición. Si la matriz
resultante posee una diagonal estrictamente dominante, deberán escribir 1 en el registro a0 (Revisar green
card de la sección Assembly) y terminar el programa, de lo contrario, deberán guardar 0 en el registro a0 y
terminar el programa."

Esto significa que no podemos escribir nada en el registro a0 previo a revisar si la matriz es invertible?, lo pregunto porque en mi código implemente de que la matriz parte con la condición que me indica de sí es invertible como verdadera, el a0 tiene un 1 y si no cumple cierta condición esta cambia ,el a0 ahora almacena el 0, me refiero a que antes de revisar si la matriz es invertible  ya he escrito en el a0.

**Comment by tocococa** [comment]
Hola!

No, puedes usar `a0` para lo que quieras durante la ejecución de tu programa, pero cuando termine, debes indicar con 1 o 0 en `a0` el resultado del algoritmo.

**Comment by RonaldoSosa** [comment]
Yaaa gracias :)
