### ISSUE TITLE
Notas T1

### ISSUE THREAD

**Issue by folozano** [IIC2343/syllabus-2021-1#35]
Hola! Quería preguntar cuando van a estar las notas de la T1. Gracias.

**Comment by tocococa** [comment]
Hola, como tuvimos la semana de receso entremedio, el plazo para la entrega de las notas es hasta el jueves de esta semana, así que están a más tardar ese día.

**Comment by folozano** [comment]
¿Qué pasó finalmente?

**Comment by tocococa** [comment]
Tuvimos un pequeño problema porque uno de nosostres se traspapeló con las fechas, pero voy a publicar las notas en un par de minutos, perdón por el atraso /_ \

**Comment by folozano** [comment]
0 atao, gracias
