### ISSUE TITLE
Recorrecion T01

### ISSUE THREAD

**Issue by FJavierOss** [IIC2343/syllabus-2021-1#36]
Queria saber si se pueden subir los tests que se utilizarón para corriger la T01, para poder confirmar así los comentarios de la corrección.

**Comment by tocococa** [comment]
Hola, no, lamentablemente los tests no van a ser subidos, si sientes que el feedback que quedó en tu corrección es insuficiente, te pido que por favor nos mandes un correo al mail del curso.
