### ISSUE TITLE
Extensión preguntas de desarrollo T02

### ISSUE THREAD

**Issue by Drpinto1** [IIC2343/syllabus-2021-1#37]
¡Hola! 🌚

En el enunciado se menciona que las respuestas a la parte de desarrollo no pueden superar una plana de extensión.
Este límite es para cada sección de la pregunta (las dos de caché y la de punto flotante) o para el conjunto de las 3?

¡Saludos! 🌝

**Comment by tocococa** [comment]
Hola!

En conjunto para las 3 no se debe superar la plana de extensión. Lamento el requisito, pero si no jamás vamos a terminar de corregir (#｀-_ゝ-)

**Comment by folozano** [comment]
Una duda, si saqué información sobre el funcionamiento del caché desde internet y lo cito en una bibliografía, ¿eso está incluido en el máximo de 1 plana? ¿Puedo tener la bibliografía en una segunda plana?

**Comment by tocococa** [comment]
Hola @folozano , si tienes bibliografía puedes dejarla en otra página, no te preocupes.
