### ISSUE TITLE
Tamaño Matriz Tarea 2

### ISSUE THREAD

**Issue by diegovaras97** [IIC2343/syllabus-2021-1#38]
Hola!

Me preguntaba que dimensiones puede tener la matriz que se generará con los nodos hoja para la Tarea 2

Gracias!

**Comment by tocococa** [comment]
Hola!

El tamaño de la matriz será lo suficientemente grande para que los algoritmos de determinante clásicos (2x2, 3x3, 4x4) no sirvan y deban implementar una solución genérica, pero no lo suficientemente grandes para que sus computadores se queden pegados resolviendo. En la tarde voy a subir algunos ejemplos para que prueben y creo que la más grande que hay por ahora es de 6x6.

**Comment by fcartoni** [comment]
Hola! Es posible que nos pongan en A solo un 0? ¿Qué debemos responder en ese caso? Porque es simétrica pero no tiene hojas para calcular un determinante. Gracias!

**Comment by tocococa** [comment]
@fcartoni en ese caso debiesen responder que no es posible calcular el determinante, pueden reusar el mensaje de que no es cuadrada nomás.
