### ISSUE TITLE
Dudas sobre cálculo de determinante en T2

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2343/syllabus-2021-1#39]
Hola! Que no entendí a partir del enunciado de la T2 como se calcularía el determinante de una matriz cuyas entradas son solo letras. En el ejemplo del enunciado, tenemos una matriz [[a; b]; [c; d]]. En los casos de prueba, ¿tendremos números enteros en estos espacios?

**Comment by joaquineichholz** [comment]
En la ayudantía dijeron que serán números distintos de 0 y 1.

**Comment by tocococa** [comment]
Hola!

Efectivamente en el enunciado son letras, pero es solo para ejemplificar (aunque igual podrías interpretar esas letras como números (⊙_⊙)？). En la tarde voy a subir ejemplos con números, pero como dijo @joaquineichholz, para facilitarles un poco la vida, el valor de 'a' (el primer dígito), no va a ser ni 0 ni 1.

**Comment by mvaldes12** [comment]
Hola! En la ayudantía se dijo que no se puede usar recursión, pero para calcular el determinante no se me ocurre otra forma para hacerlo. Siento que si no se puede tendría que saber el número de nodos para calcular manualmente cada caso.

No se puede usar recursión porque assembly no lo soporta? o por qué?

Quedo atenta
Gracias

**Comment by tocococa** [comment]
Hola @mvaldes12, perdón si se entendió que no podían usar recursión, pero lo que quería decir es que no _recomiendo_ que usen recursión, recuerda que cualquier algoritmo recursivo puede ser escrito de manera iterativa.

**Comment by mvaldes12** [comment]
Ah ya bacán, pero por qué no se recomienda? En clases vimos como llamar una función dentro de otra entonces no veo porqué esto es distinto!

Muchas gracias!

**Comment by tocococa** [comment]
Es más que nada porque al hacerlo de forma iterativa, tienes que pasar manualmente los datos y tienes un poco más de control sobre uso de memoria y se hace un poquito más fácil el debuguear, pero si se te hace más fácil programarlo de manera recursiva, eres libre de hacerlo así.

**Comment by mvaldes12** [comment]
gracias!

**Comment by fediaz3** [comment]
Una pregunta, es que en general en la forma iterativa para recorrer arboles, se necesita modificar una estructura de datos. En RISC-V existe alguna forma para simular un array fuera de la sección data? de manera que la pueda ir modificando? 

Gracias!

**Comment by tocococa** [comment]
Hola @fediaz3 , RISC-V no tiene soporte para ningún tipo de estructura más allá de poder almacenar datos de manera contigua en memoria. Si necesitas espacio extra, puedes asignar una especie de "buffer" entre labels en la sección `.data` con la directiva `.space`, pero recuerda que como los datos se almacenan de forma contigua y el heap crece hacia arriba, puedes continuar almacenando datos a partir de lo último que definiste en la sección `.data` sin sobrescribir nada de lo definido en la sección `.data`. Para facilitarlo puedes dejar un label al final de la sección `.data` y así siempre sabes dónde se acaban tus datos y puedes seguir escribiendo.

**Comment by constanzacontreras** [comment]
Hola!  Tengo dos preguntas!
1) no entiendo bien esto "Para facilitarlo puedes dejar un label al final de la sección .data y así siempre sabes dónde se acaban tus datos y puedes seguir escribiendo.". Me podrías dar un ejemplo de como funcionaría algo así? Me confunde el uso de variables en memoria. 
2) Si yo defino un array auxiliar (de tamaño variable) abajo de N, no debiesen chocar los elementos en memoria? Estoy muy confudida de como usar variables en el data.

Muchas gracias!

**Comment by tocococa** [comment]
Hola @constanzacontreras, eso esta explicado en la issue #57.
