### ISSUE TITLE
Duda números posibles y problemas de borde T1-RISC-V

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2343/syllabus-2021-1#4]
Hola!

Tengo unas dudas sobre el enunciado que posterior a la tabla de nombres se menciona: "Deberán trabajar sólo con enteros, con signo o sin signo, de a lo más 8 bits, .byte en RISC-V. Además de tomar las precauciones necesarias para manejar condiciones de borde."
1.  Acá se refieren a que la matriz puede tener tanto números positivos como negativos, ¿cierto?  no necesariamente de un signo.
2.  En cuanto al tamaño de los números, de que estos no pasarían del byte ¿se refiere a lo que salía antes del intervalo de los a_{ij} de [-127, 127]?  Sin considerar el travieso -128.
3. En relación a lo anterior, ¿ a qué se refiere explícitamente con el manejo de condiciones de borde? en teoría RISC-V no debería explotar con las restricciones que pusieron, pero si me equivoco,  ¿podrían dar un ejemplo en el que debamos considerar estas condiciones?  lo agradecería mucho.

Gracias de antemano. 
Saludos!

**Comment by tocococa** [comment]
Hola!

En el enunciado explicamos que una matriz puede contener valores en el intervalo [-127, 127]. Como tu mismo dijiste, no vamos a incluir el -128. Por lo tanto los valores de la matriz los deben cargar como números con signo, ya que pueden ser negativos o positivos y no necesariamente todos del mismo signo como preguntabas.

Con condiciones de borde nos referimos a situaciones en que puedan tener un número que no pueda ser representado adecuadamente con 8 bits, y por lo tanto al guardarlo/cargarlo/operar con el, como si fuera un numero de un byte, obtendrán un resultado inesperado.
El emulador no les va a dar ninguna pista de que esto ha ocurrido, más allá de mostrar una representación de un número que tal vez no calce con lo que ustedes esperaban. Por ejemplo, podrías tener un entero muy grande donde esperabas tener un negativo o un negativo muy negativo donde esperabas tener un positivo más o menos grande, pero todo eso depende de cómo sen sus implementaciones en particular.

**Comment by Jamesmoreno21** [comment]
Muchas gracias por la respuesta! Me quedó claro el tema del rango, pero aún no entiendo bien qué caso borde se podría dar ¿uno con  "overflow"?  Como en la sumatoria quizás sumar números mayores a un cierto valor límite podría ser. De ser así, ¿se nos tiene que ocurrir cómo manejar los bordes overflow?

**Comment by tocococa** [comment]
Efectivamente un caso en que ocurra overflow sería un caso de borde, y claramente se les tiene que ocurrir a ustedes como manejarlo ya que es uno de los objetivos de la tarea.

**Comment by Jamesmoreno21** [comment]
Okey, muchas gracias :)
