### ISSUE TITLE
Sección 'Output' de la T2

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2343/syllabus-2021-1#40]
Hola! Que leyendo el enunciado me quedaron muchas dudas sobre la sección Output de está. 'Output' lee:

"Al finalizar la ejecución, deberán utilizar la environment call Ecall = 1, PrintInt para imprimir en
consola el determinante de la matriz, si este fue calculado, Ecall = 4, PrintString o Ecall = 64, Write,
para indicar si el árbol no es simétrico o la matriz no es cuadrada, y finalmente Ecall = 10, Exit para
salir."

No entiendo que son estás Ecall, y también siento que esta medio confuso la forma en que la explicaron. Si me pudieron explicar más fácil lo agradecería muchísimo.

Saludos,

**Comment by tocococa** [comment]
Hola!

Te recomiendo revisar el código que se subió junto a la ayudantía del viernes pasado, donde se muestra cómo utilizar los environment calls (ecalls). En el emulador también está explicado cómo usarlas, en Help>Syscalls.

Si aún así tienes dudas, por favor escribe acá!

**Comment by joaquineichholz** [comment]
En el emulador > Help > syscalls estan especificados los ecalls que puedes hacer (son 65 acciones posibles)

Cuando llamas a ecall, lo que hace es revisar el registro a7 y ver el numero que tiene guardado. Dependiendo de eso hace diferentes acciones. 

Por ejemplo el ecall = 1 (a7 = 1) corresponde a PrintInt. 

De esta forma si haces: 
     
    li  a7, 1          # service 1 is print integer
    li a0, 5
    ecall

Esto imprimira un "5" en consola

**Comment by dpacevedo** [comment]
Hola!

Tengo una duda respecto al output, en el enunciado se menciona que debemos verificar la simetría del árbol y si el árbol es simétrico, verificar que se pueda construir una matriz cuadrada y, si es posible construir la matriz, calcular y retornar el determinante de esta. Por lo tanto, si no es simétrico podemos simplemente indicar que no lo es y terminar el programa, sin la necesidad de determinar si es posible calcular una matriz cuadrada con las hojas y calcular el determinante? Me surgió la duda porque en los árboles de prueba se indica en todos los casos la simetría, si es posible construir una matriz cuadrada y su determinante.

Muchas gracias! 🌻

**Comment by tocococa** [comment]
Hola @dpacevedo ! Efectivamente, si el árbol no es simétrico, pueden indicarlo y acabar el programa, voy a ir agregando casos de prueba a medida que surjan dudas.

**Comment by fcartoni** [comment]
Hola! Puedo usar la Ecall = 4, PrintString para cuando no es simétrica y también para cuando no es cuadrada? Que siento que está mal redactada esa parte en el enunciado y no entiendo si hay que usar también la ecall 64. Gracias :)

**Comment by tocococa** [comment]
Hola @fcartoni, si, puedes usar esa Ecall mientras dejes claro cuál es la conclusión de tu algoritmo.
