### ISSUE TITLE
Material Subrutinas 

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2343/syllabus-2021-1#41]
Hola! Alguien que tenga buen material sobre subrutinas para aprender a utilizarlas en risc-v? 

Gracias!!

**Comment by tocococa** [comment]
Hola!

Acá hay algunas referencias:

https://bt.nitk.ac.in/c/18b/co200/notes/2.4.SubroutineCalls.pdf

https://inst.eecs.berkeley.edu/~cs61c/fa17/lec/06/L06%20RISCV%20Functions%20(1up).pdf

https://medium.com/swlh/risc-v-assembly-for-beginners-387c6cd02c49

Lo importante es saber para qué se debe usar cada registro, el uso de las instrucciones `jal` y `jarl` y la forma de guardar cosas en el stack (si lo llegaras a usar). Igual ojo que por pauta el uso de subrutinas es una _sugerencia_, no vamos a entrar a indagar a su código salvo para revisar la convención de llamada y si hay algo que no funciona.
