### ISSUE TITLE
Definición de Árbol Simétrico

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2343/syllabus-2021-1#42]
Hola! Que no sé cuál es la definición de un árbol simétrico. ¿Sería posible que nos den la definición de un árbol simétrico?

**Comment by tocococa** [comment]
Hola!

La definición de árbol simétrico es que sea simétrico por su centro (un espejo de si mismo, a lo largo de su centro). El siguiente árbol es simétrico:
![image](https://user-images.githubusercontent.com/22779371/121939999-a28ea300-cd1b-11eb-84f5-b0d4ee47c74d.png)
Y este no es simétrico:
![image](https://user-images.githubusercontent.com/22779371/121940049-afab9200-cd1b-11eb-8d3c-34b2672b9201.png)

**Comment by raimundomartinez** [comment]
Ya muchas gracias. Se entiende perfect la definición, pero me parece algo extraña porque tenía entendido que los grafos (árboles) eran esencialmente conjuntos (G = (V,A) donde V y A son conjuntos) y que esos dibujos eran simplemente representaciones gráficas, de las cuales hay muchas más posibles. Por ejemplo, en el ejemplo que diste de un árbol no simétrico, un árbol que si es simétrico (con el nodo 3 de la derecha en posición izquierda en vez de derecha), a nivel de su definición como un conjunto, sería exactamenre igual al no simétrico.
El segundo árbol (el no simétrico) en verdad es el par ordenado:
G = (V, A), con V = {1,2a,2b,3a,3b} y A = {(1,2a),(1,2b),(2a,3a),(2b,3b)}
Y ese árbol se puede perfectamente dibujar como un árbol simétrico.
Si nos dicen que ignoremos todo esto está bien, pero me queda un poco la inquietud.

**Comment by raimundomartinez** [comment]
Otra pregunta, si tenemos el siguiente árbol
![Captura de Pantalla 2021-06-14 a la(s) 14 44 27](https://user-images.githubusercontent.com/48482564/121943043-2b5b0e00-cd1f-11eb-8de2-85ae0a50a88c.png)
:


según la explicación que me dieron, ¿este árbol sería simétrico sólo si a = d y b = c ?

**Comment by tocococa** [comment]
Nono, los valores de los nodos hoja del último nivel pueden ser cualquier cosa, la propiedad de simetría, en este caso, es independiente al peso de cada nodo. Ese árbol sería simétrico.

Respecto a tu duda anterior, es verdad que un árbol puede ser dibujado de casi cualquier manera (cualquier nodo puede ser una raíz), pero en la representación que les entregamos se indica cuál se considerará raíz y a partir de ese tienen que ver si es simétrico o no. Hay situaciones en que es conveniente ordenar un árbol de cierta forma para recorrerlo más fácilmente, poder concluir algunas cosas más rápido o modificarlo sin demasiados pasos extra, y en el caso de esta tarea, la forma en que se construyen es a partir de una raíz y de ahí hasta llegar a los últimos nodos que arman la raíz, aunque en rigor nada te impide construir el mismo árbol a partir de cualquier otro nodo.
