### ISSUE TITLE
Overflow T2

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2343/syllabus-2021-1#43]
Hola, no me quedo claro con el enunciado si es que debemos considerar en el código o no el manejo de overflow

**Comment by tocococa** [comment]
Hola, eso queda a criterio de ustedes, pero mi recomendación es al menos hacer un chequeo de límites estilo `0<= x <= y`, y si los tratas como número sin signo, `x<y` atrapa tanto el caso en que `x` es negativo y el caso en que `x` es menor a `y`.

**Comment by faguilerag** [comment]
Hola!! estoy confundida, en uno de los arboles de prueba dice que tiene 163 nodos, cuando lo paso por mi programa me arroja el -93, asumi que es el overflow, pero no recuerdo hasta que numero soportaba risc-v? o hasta que numero debemos ser capaz de mejorar con nuestro programa?

**Comment by tocococa** [comment]
Hola @faguilerag, RISC-V por defecto trabaja con representaciones de 32 bits. No me queda claro si te está danto overflow al cargar el 163 o al calcular el determinante, pero si no me equivoco, en ese test el valor del determinante NO es representable con 32 bits en complemento de 2. Para el manejo de overflow, puedes pasarte a 64b o terminar con un error adecuado, mientras dejes un comentario justificando tu decisión, es suficiente.

**Comment by faguilerag** [comment]
@tocococa es que si eso lo entiendo, pero me esta pasando algo extraño, como que cuando guardo el numero de nodos (en este caso 163) me tira a overflow, como si estuviera con 7 bits (hasta el 127), me esta pasando unicamente cuando guardo el numero de nodo, cuando debo hacer sumas no me pasa :(( y no se si sera un problema de configuración o soy yo
