### ISSUE TITLE
Problema al usar 2 blocks 2 words

### ISSUE THREAD

**Issue by folozano** [IIC2343/syllabus-2021-1#44]
Hola! 

Quería preguntar si realmente es recomendado para la pregunta "Caché Lindo" usar 2 block y 2 words. 

Al hacer eso obtengo resultados muy monótonos, mientras que si uso los valores predeterminados tengo mejor material para comentar. Es por esto que me gustaría usar los valores predeterminados para mi análisis.

**Comment by tocococa** [comment]
Hola, si prefieres usa otra configuración, debes justificar por qué, pero la idea de la tarea siempre es que exploren y aprendan, así que ningún problema.
