### ISSUE TITLE
Duda árboles de test

### ISSUE THREAD

**Issue by Tvergara** [IIC2343/syllabus-2021-1#45]
Hola, puede ser que en el test 3 el N debiese ser 163 (que faltó una coma en el árbol justo antes de empezar con la matriz)?

También, el resultado del test es un número que no se puede representar en 32 bits, eso significa que está permitido operar con registros de 64 bits?

**Comment by tocococa** [comment]
Hola, efectivamente es un 163 (terrible que se me haya pasado porque no pueden haber árboles con nodos pares (* ￣︿￣)).

Que el resultado no sea representable con 32 bits queda a criterio de ustedes, puedes alegar por overflow y terminar la operación, pasarte a 64 bits, capearlo en el máximo de un entero sin signo para 32b. Ahí queda a tu criterio mientras dejes claro que hiciste y porqué.
