### ISSUE TITLE
Numero combinaciones [P1 Desarrollo] [Tarea 2]

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2343/syllabus-2021-1#46]
Hola, se que lo proeguntaron en la ayudantia de repaso para la tarea pero no me quedo claro. Mi pregunta es si para la parte "caché lindo", debemos probar las 6 combinaciones existentes de Placement Policy y Block Replacement Policy, o con un par esta bien. Muchas gracias!

**Comment by tocococa** [comment]
Hola!

Idealmente con todas las combinaciones, pero la idea de la pregunta es que aprendan como funciona la memoria caché y el impacto del programa y las políticas de ubicación y sustitución en el rendimiento. Idealmente prueba con todas las combinaciones para irte a la segura (ojo que el resultado no es tan increíble como se podría esperar).

**Comment by tomasalvarez13** [comment]
Perfecto muchas gracias!

**Comment by fediaz3** [comment]
hola! una pregunta, es que he hecho todas las combinaciones distintas y al ver los resultados finales, son todos iguales en las estadísticas finales :/, estaré haciendo algo mal? o se espera que comparemos lo que aparece en runtimelog? (que eso me aparece con algunas variaciones)

**Comment by tocococa** [comment]
Hola @fediaz3, en esta pregunta tienes dos opciones, o explicar porqué los resultados son casi iguales, o decir que no te gustaron los resultados, explicar porque consideras que sería necesario cambiar el tamaño del cache, trabajar con eso y explicar las diferencias.
