### ISSUE TITLE
Plazo tarea 2

### ISSUE THREAD

**Issue by mvaldes12** [IIC2343/syllabus-2021-1#47]
Hola!

Me gustaría saber si hay alguna opción de dar un poco más de plazo para la tarea!
Sería de mucha ayuda!

Muchas gracias!!

**Comment by fcartoni** [comment]
Yo también apoyo que den más plazo!!! Me estoy demorando mucho más de lo que pensé en esta tarea :( Gracias!!!

**Comment by mimunoz11** [comment]
Me sumo a lo dicho anteriormente!

**Comment by adbakulic** [comment]
Yo también estoy de acuerdo con que se aplace la tarea, por favor!

**Comment by jadawabe** [comment]
De acuerdo con todos los comentarios que han dicho

**Comment by fivaldivia** [comment]
Yo también! Tenía muchas cosas para estas semanas lo que me deja muy poco tiempo para la tarea!

**Comment by humbertoortuzar** [comment]
Me sumo a la petición, agradecería mucho si se puede considerar!

**Comment by aiarias** [comment]
Siii porfavor, un poco más de tiempo se agradeceria muchisimo!

**Comment by Dnpoblete** [comment]
Sii por favor, se agradecería mucho 🥺

**Comment by juansjimenez** [comment]
Me sumo, plsss

**Comment by MINGOD24** [comment]
Estoy de acuerdo, estaría bacan un poco más de tiempo.

**Comment by tomasgv** [comment]
Me sumo a la petición, apreciaría muchísimo algo más de tiempo ❤️

**Comment by constanzacontreras** [comment]
Si por favor que se de más tiempo! se agradecería mucho!! el fin de semestre está muy intenso, y nos aliviaria la carga academica!

**Comment by vikicontardo** [comment]
Yo igual me sumo al pedido!! Sería de GRAN ayuda un plazo extra. Muchísimas gracias de antemano equipo docente <3

**Comment by rbhernandez** [comment]
Me sumo! sería de muchísima ayuda 😢

**Comment by barbaraim** [comment]
Yo también me sumo! Ayudaría mucho!

**Comment by macavarelau** [comment]
Por favor! Habríamos muchos agradecidos :(

**Comment by ctronp** [comment]
Seria de mucha ayuda, el estrés esta por las nubes

**Comment by diaztunjano** [comment]
Me sumo a todo lo anterior, seria de mucha utilidad! Muchas gracias 🙌🙌

**Comment by fcartoni** [comment]
Siii y además para la T1 tuvimos 1 mes y era cortísima! Ahora dos semanas y es MUCHÍSIMO más larga!! :(

**Comment by mjgarrido1** [comment]
Hola! me sumo a las peticiones de mis compañeros, se me juntaron todas las evaluaciones :( gracias!

**Comment by EstebanReyes1998** [comment]
Me sumo a la petición

**Comment by ivigiglio** [comment]
Sii por favor estoy de acuerdo!

**Comment by elisafdz** [comment]
Si! Está mucho más larga esta tarea, nos ayudaría mucho tener más plazo.

**Comment by joaquineichholz** [comment]
Sería  bueno tener más tiempo, la tarea esta larga y difícil. Además estamos con muchas cosas en todos los ramos y no queremos dejar cosas a medias. 

dejo un += 1 en risc-v para que tengan compasión 

```
.globl start

 start: 
     li a0, zero 
     addi, a0, a0, 1 

end: 
```

**Comment by ajuanchuto** [comment]
Yo también me sumo a mis compañeros y compañeras, ojalá se pueda dar más plazo. Muchas gracias !! 😄

**Comment by fsotomutoli** [comment]
Me sumo a mis compañeros, estaría de lolo que den más plazo. De ser posible, muchísimas gracias!

**Comment by francisca0308** [comment]
Me sumo también!

**Comment by RonaldoSosa** [comment]
Me sumo también, se agradecería mucho que dieran más plazo

**Comment by dpvillarroel** [comment]
Me sumo también! 😭

**Comment by hsazos** [comment]
Me sumo!

**Comment by jitorcas** [comment]
Me sumo también!

**Comment by fddelabarra** [comment]
Me sumo 😅 se me juntaron varias cosas y está difícil "patear" alguna de ellas 😥

**Comment by fernandovegauc** [comment]
Estaría muy agradecido con un par de días más de plazo :shipit:

**Comment by FelipeBodelon** [comment]
Apoyo fervientemente la moción.

**Comment by tatanpoker09** [comment]
![image](https://user-images.githubusercontent.com/6262015/122327036-39658600-cefb-11eb-8ede-5b2ffd26f6e1.png)

**Comment by beatrizacuna** [comment]
yo tambien me sumo  😅
