### ISSUE TITLE
Construcción de la matriz T2

### ISSUE THREAD

**Issue by szabala** [IIC2343/syllabus-2021-1#48]
Hola, despues de leer el enunciado me queda la duda sobre como se construye la matriz a partir de los nodos del árbol. En el enunciado se indica que:  

> Si el número de nodos hoja en el último nivel es tal que se puede construir una matriz cuadrada usando todos los valores, de izquierda a derecha y de arriba hacia abajo, se deberá calcular y retornar el determinante de dicha matriz.

Esto me genera confusión ya que se dice explícitamente que los valores a partir de los cuales se construye la matriz son únicamente los **nodos hoja del último nivel del árbol**. Sin embargo, se pide construir la matriz de "_izquierda a derecha y de arriba hacia abajo_". ¿Como definimos la verticalidad entre los valores si todos están en último nivel del árbol? ¿o se refiere a insertar las parejas de nodos en ese orden para tratar de armar una matriz cuadrada?

No me queda muy claro por cómo esta formulado en el enunciado 😅

**Comment by tocococa** [comment]
Hola @szabala ! Se refiere a que la matriz se va rellenando en ese orden, en el ejemplo con los valores `a, b, c, d` para las hojas del último nivel, se construye la matriz `[[a, b], [c, d]]`. El primer nodo hoja que aparece en la representación ocuparía el primer valor de la matriz y de ahí hacia adelante se rellena en el orden indicado en el enunciado (de izquierda a derecha y de arriba hacia abajo).

Perdón si no quedó totalmente claro en el enunciado.

**Comment by szabala** [comment]
Gracias!

**Comment by humbertoortuzar** [comment]
Hola! Si tenemos por ejemplo: a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p
Esto sería la matriz:
[
[a, b, c, d],
[e, f, g, h],
[i, j, k, l],
[m, n, o, p]
]
?

**Comment by tocococa** [comment]
Sí, exactamente de esa forma.
