### ISSUE TITLE
Velocidad de ejecución tarea 2

### ISSUE THREAD

**Issue by fcartoni** [IIC2343/syllabus-2021-1#49]
Hola! Me está pasando algo muy raro, cuando corro la tarea con una velocidad baja, me recorre bien la matriz y me hace bien los determinantes, pero si lo corro a la velocidad predeterminada (que es lo más rápido) es como si se "confundiera" con los valores de los registros, o no los alcanza a actualizar y me funciona pésimo. ¿Es normal? Puedo decir que se tiene que correr a una velocidad baja no más? O que está pasando? 
Gracias :)

**Comment by tocococa** [comment]
Hola @fcartoni ! Es probable que sea un _bug_ del emulador, me di cuenta con el programa `moon.asm` que eso podía pasar. Lo único que te puedo sugerir (no somo los mantenedores del emulador) es que lo ejecutes lo más rápido que puedas sin pasar a máxima velocidad <( _ _ )>

**Comment by fcartoni** [comment]
Ahhh ya!! O sea en mi tarea especifico a la velocidad que la tienen que correr para que no se eche a perder?? Muchas gracias!!!!! :)

**Comment by tocococa** [comment]
Sip, puedes dejar un comentario al principio del programa.
