### ISSUE TITLE
Matrices de prueba para tarea 1 y overflow

### ISSUE THREAD

**Issue by ajuanchuto** [IIC2343/syllabus-2021-1#5]
Hola!!

Quería saber si era posible que nos subieran posibles matrices con el output esperado de a0 para poder verificar si el código está correcto. Yo igual he probado con varios casos, pero no he probado con matrices tan grandes y me cuesta también saber si estoy manejando los casos bordes correctamente.

Además no entiendo bien la diferencia entre usar los registros `a` , `s` o `t`. 

Muchas gracias :smile:

**Comment by tocococa** [comment]
Hola!

Si lo necesitan les podríamos subir matrices de prueba en un par de día, pero si quieres probar con algo mientras tanto, te recomiendo probar con una matriz de 11x11 y otra con números cercanos a -127 o 127, que como les dijimos en el enunciado se tratan de los límites de tamaño y valores para la matriz. Un poco lo que queremos que hagan es pensar en que ocurre si alguno de los registros que estás usando pasa a contener un número que no se puede representar con un solo byte y tratar de minimizar el impacto que eso tendría en su programa.

La diferencia entre los registros `a`, `s` y `t`, es que `a` se utiliza para los argumentos de una función, `t` es para elementos temporales, como por ejemplo llevar la cuenta de el número de iteraciones en un loop, y los registros `s` son aquellos que deben ser preservados si ocurre una llamada a otra función/subrutina/demás, por lo que antes del cambio deben ser respaldados. Si quieres leer más puedes revisar [acá](https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf).

**Comment by ljrodriguez1** [comment]
Hola, hay algo que no entiendo, en mi solución el numero mas grande que llegare a sumar es 1270, los registros son capaces de almacenar ese valor por lo que no tengo problemas, pero entiendo que ese numero es mas grande que un byte. 
No se si estoy haciendo algo que no es debido pero me serviría mucho la ayuda.

También agrego que serviría mucho que suban matrices de prueba, porque yo soy capaz de crear una pero siempre existe la posibilidad de que haya entendido mal el problema

**Comment by tocococa** [comment]
Hola @ljrodriguez1 !

Efectivamente en tu solución puedes llegar a tener números más grandes, pero estos NO pueden representarse con un solo byte. Lo que ocurre es que los registros de RISC-V son de 32 bits, independiente de que estés haciendo con ellos, por lo que si tu decidieras guardar el número 1270 en memoria utilizando `sb`, terminarías guardando sólo los primeros 8 bits de la representación de dicho número. Por la misma razón, cuando cargas de memoria a un registro, le debes indicar que tipo de representación estás cargando y para eso existen las distintas instrucciones de `load`.

**Comment by ljrodriguez1** [comment]
Esto quiere decir que a pesar de ser capaces los registros de almacenar estos valores, yo no puedo hacerlo por restricción de la tarea?

**Comment by ljrodriguez1** [comment]
Muchas gracias, pero no entiendo como se evaluara esto, revisarán que en mis registros nunca haya un valor mayor a 1 byte?

**Comment by tocococa** [comment]
No te puedo confirmar ahora, pero la idea más que nada es que puedan darse cuanta cuando habría ocurrido overlfow y lo manejen adecuadamente, y el "adecuadamente" queda a criterio de ustedes, pueden capear el número en el máximo representable o si piensas en el problema que están tratando de resolver en la tarea (ver si algo es más grande que otra cosa que sabes que ocupa a lo más un byte), saltarte algunos pasos y llegar a una conclusión. 

Al final la idea en esta parte, es que nos demuestres que sabes qué es y cuándo ocurre overflow, nada más.

**Comment by ljrodriguez1** [comment]
Okey muchas gracias, perdón por preguntar tantas cosas pero me pareció rara esa parte.

El problema de las dos soluciones que entregas es que si hago eso nada me asegura que mi código retorne la respuesta esperada. ya que si capeo, eventualmente tendría que restarle a este contador y podría terminar en un valor menor al de la diagonal cuando la suma sin capear quizá es mayor a la diagonal. con la otra solución pasa lo mismo. si es que salto pasos, quizá salte restas que hacían que el valor sea menor a el de la diagonal

Lo que en realidad tendríamos que hacer es ocupar dos registros para almacenar esta suma. lo cual no se si es la idea principal de la tarea, pero es la única forma que se me ocurre para poder asegurar de que mi código siempre retorna la respuesta correcta.

**Comment by tocococa** [comment]
Tranqui, no hay problema en hacer preguntas, pero recuerda que la fórmula que deben usar, utiliza el valor absoluto, por lo que el valor de la fila solo puede aumentar. Así no deberías tener problemas con, por ejemplo, una cota superior.

**Comment by ljrodriguez1** [comment]
Gracias, muy cierto, tenia la idea de que el valor absoluto iba afuera de la sumatoria, con esto se me acaban mis dudas, gracias!

**Comment by ljrodriguez1** [comment]
Para efectos de esta tarea da lo mismo si ocupo los registros a, s o t?

pregunto aquí por que se comento arriba.

**Comment by Jamesmoreno21** [comment]
Hola! En relación a las matrices de prueba y los tamaños, quería saber si N tiene un mínimo específico (2 por ejemplo) y un máximo (127?). Gracias de antemano!

**Comment by ajuanchuto** [comment]
@Jamesmoreno21 No soy ayudante pero en el enunciado dar los valores mínimos y máximos de N y M. 😺 

Muchas gracias @tocococa por la respuesta! 💯

**Comment by tocococa** [comment]
@ljrodriguez1 si, da un poco lo mismo si los usas intercambiadamente, pero idealmente intenta usar `a` para los argumentos de le función, `t` para iterables y cosas por el estilo y `s` se usa un poco en lo que vieron la última clase, así que puedes ignorarlos.

@Jamesmoreno21, el mínimo podría ser 1, en que se acepta la condición básicamente por vacuidad, después de eso para una matriz de 2x2 ya tienes que empezar a evaluar.

Gracias @ajuanchuto! Suerte en la tarea :3

**Comment by Jamesmoreno21** [comment]
Hola! Lamento volver a preguntar algo parecido, pero hoy en clases dijeron algo en relación a los tamaños de registros de RISC-V (que eran de 32bits), entonces mi duda va a que si el tamaño máximo de la matriz es 11x11 y la matriz que ponga en cuestión sea de puros  (+-)127 no se debería caer en un overflow en la suma porque 127*(11-1) < (2^32) - 1 necesariamente, ¿esta bien que lo piense así? o ¿el overflow puede surgir de otra forma? Gracias de antemano

**Comment by AndresGonzalez5** [comment]
@Jamesmoreno21 Piensa que pasaría si solamente vas a poder almacenar/leer 1 byte (8 bits). Los registros pueden tener valores mayores (hasta 32 bits), pero al momento de ejecutar instrucciones como `lb` o `sb` solamente trabajas con 1 byte, y si el registro tiene valores más grandes que el 1 byte entonces vas a perder los bits extra. Si tienes un número que no se puede representar con esos 8 bits entonces ya estás viendo a un caso de overflow y debes pensar cómo abordarlo.

**Comment by Jamesmoreno21** [comment]
Creo que entiendo, pero eso sería únicamente si quiero almacenar datos en la "Data Memory" no? porque si uso sólo registros para las operaciones no tendría necesidad de usar  `sb` para valores de más de 1 byte.

**Comment by raimundomartinez** [comment]
Hola! Sé que ya lo han preguntado en este foro, pero no me han quedado muy claras las respuestas. En el enunciado, dice que las entradas de la matriz van a obtener un valor entre -127 y 127. El problema que tengo, es que si la matriz es de 11x11, entonces para comprobar la condición tengo que sumar varias entradas, entonces se tiene que trabajar con números que llegan hasta 1270 (127 x 10). Lo que no entiendo, es que debemos hacer si es que ocurre esto. Por ejemplo, digamos que uno tiene la matriz M = {{10, 127, 127}, {1,3,1}, {1,1,3}}, se me ocurren dos posibilidades para solucionar el problema:
A: Trabajar con más de 8 bits (ya sea con 16 o 32 bits)
B: Al hacer la suma de 127 + 127, te da un overflow y el resultado sería -2. Uno podría detectar inmediatamente, que como el número es negativo, entonces este debió haber dado una suma mayor a 127. Como el valor de todas las entradas es de máximo 127, entonces si o si la suma superó el tamaño de la entrada a_11. Dicho esto, podemos concluir que la matriz no cumple la condición.
¿Cuál de estas dos opciones debería cumplir? Si no es ninguna de las dos, ¿que debería hacer?

**Comment by AndresGonzalez5** [comment]
@raimundomartinez Vas bien encaminado con la B, debido a que una de las ideas de la tarea es que sepan manejar los casos de overflow y llegar al resultado esperado (y ya tienes pensada una forma de manejo de estos). Con respecto al punto A, puedes almacenar numeros grandes en registros, pero debieses tener alguna forma de controlar que te pasaste de lo que puedes almacenar en un solo byte (uno de los aspectos de la tarea es que sepan trabajar con los 8 bits a pesar de tener más información de bits).

**Comment by ajuanchuto** [comment]
Hola, disculpen por volver a escribir en una issue resuelta, pero quería saber si iban a subir los ejemplos de prueba antes del lunes para los que entreguen la tarea en el plazo original, muchas gracias 😸

**Comment by tocococa** [comment]
@ajuanchuto , ya subí un par de casos para que prueben, están linkeados en el README junto al enunciado de la tarea （￣︶￣)
