### ISSUE TITLE
Recursión en T2

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2343/syllabus-2021-1#51]
Hola! Solo quería saber si es que es necesario usar recursión para efectuar la tarea 2. Pregunto esto específicamente para calcular la determinante de una matriz, ya que si la matriz es más grande que 2x2, uno debería calcular las subdeterminantes de las submatrices, lo cual se haría recursivamente. Agradecería mucho si me indicaran alguna forma de hacer la tarea sin usar recursión, ya que esta dificil usarlo en RISC-V. Y si es que si hay que usar recursión, cualquier tip se aprecia muchísimo.
Saludos.

**Comment by tocococa** [comment]
Hola @raimundomartinez !

Cualquier algoritmo recursivo puede plantearse de manera iterativa y viceversa, así que si te sale demasiado difícil implementar una solución recursiva, puedes intentar pensar en su equivalente iterativo. En la issue #39 hay algunas preguntas y respuestas que tal vez te podrían servir.
De todas formas, en RISC-V, para implementar recursividad, puedes usar las instrucciones `jal`, `jr` y el stack para construir funciones recursivas. El siguiente código es un ejemplo de función recursiva, que calcula el factorial de un número:
```Ruby
.globl start

.text
	start:

    li sp, 0  # seteamos el stack pinter en 0
    li a0, 3  # numero a calcular su factorial
    jal ra, fact  # llamamos a factorial(n=3) y guardamos la direccion actual direccion en ra

    li a7, 1
    ecall
    li a7, 10
    ecall

    fact:
        blt zero, a0, rec  # revisamos si es el caso base n = 0
        li a0, 1 # cargamos 1 en a0
        jalr zero, 0(ra) # llamamos a la funcion que recupera del stack, se deja ra en 0

    rec:
        sw ra, -4(sp)  # guardamos la direccion de retorno al stack (lo que habia del ultimo jarl)
        sw a0, -8(sp)  # guardamos el valor de a0 en el stack
        addi sp, sp, -8  # desplazamos el stack

        addi a0, a0, -1 # n - 1
        jal ra, fact  # llamamos a factorial(n-1) y guardamos esta direccion en ra

    addi sp, sp, 8 # retrocedemos en el stack
    lw ra, -4(sp) # recuperamos ra
    lw t0, -8(sp) # recuperamos el valor de n para esa llamada
    mul a0, t0, a0 # n * factorial(n-1)
    jalr zero, 0(ra) # volvemos a a la direccion anterior hasta llegar al valor original
```
