### ISSUE TITLE
Strings en RISC-V

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2343/syllabus-2021-1#52]
Hola! Que en mi programa de RISC-V, quiero trabajar con más de un string, pero cuando hago esto al usar ecall = 4 se imprime todos los strings para abajo. Por ejemplo, si tengo el siguiente código:

.data
    string:	.ascii "Esto es un string!\n"
    string2:	.ascii "ejemplo\n"
    numero:	.word 42
    label_generico: 

.text
_start:
    la    a0, string    # Linea 1
    addi  a7, zero, 4   # print string system call -> requires a null-terminated string!
    ecall               # call emu to output the string

OUTPUT:
Esto es un string!
ejemplo

En este ejemplo, se imprime todo desde 'string' para abajo, pero solo quiero imprimir 'string'. ¿Como puedo hacer esto?

PD: se imprime desde 'string' para abajo. Si cambio 'string' por 'string2' en la Linea 1, el output sería:

OUTPUT:
ejemplo

**Comment by tocococa** [comment]
Hola @raimundomartinez, fue un typo mío en el código de ejemplo, deben estar terminados con `\0` en lugar de `\n` para que funcione.
