### ISSUE TITLE
[Tarea 2] Duda enunciado

### ISSUE THREAD

**Issue by Tvergara** [IIC2343/syllabus-2021-1#53]
Hola, de esta parte del enunciado:

> Deberán escribir un programa que sea capaz de recorrer una codificación particular de un  árbol binario, y si el  árbol es simétrico, verificar que se pueda construir una matriz cuadrada con los valores contenidos en las hojas del  ́ultimo nivel del  árbol, si es posible construir la matriz, calcular y retornar el determinante de esta.

Entendí que si es que el árbol no es simétrico, entonces podemos avisar de eso y no es necesario concluir si la matriz es cuadrada ni su determinante. Sin embargo en los tests subidos concluyen si la matriz es o no cuadrada y el valor de su determinante también para los árboles simétricos.

Es necesario implementarlo tal que se concluya acerca de si la matriz es o no cuadrada y su determinante cuando el árbol no es simétrico?

**Comment by tocococa** [comment]
Hola @Tvergara , esto está respondido en la issue #40, pero lo repito acá nomás, si el árbol no es simétrico, debes indicar que no lo es y terminar el programa.

**Comment by Tvergara** [comment]
No había cachado, muchas gracias!

**Comment by tocococa** [comment]
De nada!

**Comment by mpbosnic** [comment]
Hola!

Resulta que para hacer la tarea, definí mi output según los ejemplos que subieron y cuando el árbol no es simétrico, de todas maneras verifico si la matriz es cuadrada. Ahora vi esta issue y no se si debería cambiarlo. ¿Estaría bien revisar si la matriz es cuadrada (con su output correspondiente), aun si el grafo no es simétrico?

Saludos!

**Comment by tocococa** [comment]
Hola @mpbosnic, da lo mismo si revisas o no si la matriz es cuadrada, lo importante es que al final de la ejecución indiques que el árbol no es simétrico.

**Comment by mpbosnic** [comment]
Gracias por la respuesta!
