### ISSUE TITLE
Cálculo raiz cuadrada

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2343/syllabus-2021-1#54]
Hola, tengo la siguiente duda. En `s4` tengo almacenado un valor `.word`, y me gustaría sacarle la raiz cuadrada, pero al usar el comando `fsqrt.s s4, s4, dyn` me dice que s4 no es del tipo correto, lo que es logico porque no es un float. PEro trato de pasarlo a float usando `fcvt.s.w s4, s4, dyn` y me sigue diciendo que `s4` no es el tipo correcto. Como puedo hacerlo para convertir `s4` a un float?

**Comment by tocococa** [comment]
Hola @tomasalvarez13, para cualquier operación con números de punto flotante debes utilizar los registros para punto flotante (`f0 - f31`). Necesitas pasar el valor de `s4` a algún registro de punto flotante de luego operar con él.
