### ISSUE TITLE
[T2] overflows en multiplicaciones

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2343/syllabus-2021-1#55]
Hay alguna forma de saber si ocurrió un overflow después de una multiplicación?

**Comment by tocococa** [comment]
Si, puedes comparar el resultado con los valores anteriores y revisar si calzan los signos, siguiendo un criterio similar al de los casos de suma o resta. También realizar una división y si uno de los multiplicandos no es 0, ver si el número es el mismo.

**Comment by constanzacontreras** [comment]
Hola!! En la misma línea de overflow. Al definir addi t0, zero, 2147483646. Me retorna el siguiente error al compilar: operand is out of range. Esto a que se debe? ya que por enunciado nos dijeron que el numero máximo era 2147483647.

Estoy atenta! muchas gracias

**Comment by tocococa** [comment]
Hola @constanzacontreras , eso ocurre porque la instrucción `addi` tiene solo 12 bits disponibles para ocupar con el inmediato:
![image](https://user-images.githubusercontent.com/22779371/122991938-96d25a80-d373-11eb-92f6-cb88d53abb52.png)
Los registros si pueden guardar un número de ese tamaño.
