### ISSUE TITLE
[Tarea 2] Números negativos en la matriz

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2343/syllabus-2021-1#56]
Hola! Quería saber si en los números de la matriz (a b c d) nos podían entregar números negativos. Muchas gracias! 😄

**Comment by tocococa** [comment]
Hola @beatrizacuna , en el README del repositorio, junto con el link al enunciado hay un archivo con árboles de prueba y creo que todos tiene al menos un negativo.
