### ISSUE TITLE
[T2] Cálculo determinante

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2343/syllabus-2021-1#57]
Hola 😸   estoy bloqueadísima con cómo hacer el cálculo del determinante en assembly, y me preguntaba si nos podrían dar algún tipo de hint para resolverlo por favoooooooooor, ya vi todas las issues e investigué 🙏

**Comment by tocococa** [comment]
Hola @beatrizacuna! Así como mega hint, hay más algoritmos para calcular el determinante que el típico que se ve en álgebra lineal y las matrices que les entregamos tienen sólo números enteros, así que eso podría ayudarles en algunas cosas.
También recuerden que pueden usar el heap para guardar valores sobre los que no saben cuántos van a tener antes de iniciar el programa y también tienen disponible el stack para su uso. 

No se que mucho más contarles sin quitarles el momento "ahá" que se tiene cuando un pilla la solución a algo.

**Comment by beatrizacuna** [comment]
y me podrías dar un ejemplo de cómo se usa el heap? que busqué y no entendí mucho 🤕

**Comment by tocococa** [comment]
Por supuesto, el heap es toda la memoria que puedes utilizar de manera dinámica y a diferencia del stack, que es jerárquico (PUSH/POP), puedes acceder a cualquier parte del heap en cualquier momento. En RISC-V, la memoria se organiza de la siguiente manera:
![image](https://user-images.githubusercontent.com/22779371/122622271-2b804400-d066-11eb-9263-69b9351dbc66.png)
El heap vendría a ser lo que se indica como Dynamic data y comienza donde termina la sección Static Data, que corresponde a toda la memoria pedida en la sección `.data` de tu programa. Como tu sabes donde termina tu sección estática, puedes almacenar datos en el heap a partir de esa dirección y hacia direcciones de memoria más altas. Para guardar las direcciones de las cosas que tienes en el heap, dependiendo de la estructura de tu algoritmo y tu programa, puedes dejar labels predefinidos, el stack o el mismo heap, mientras te acuerdes de cuál es el offset necesario.

**Comment by beatrizacuna** [comment]
Entiendo mucho mejor, muchas gracias @tocococa  😄   eso si aún tengo dudas:

1. No sé donde se usa syscall 9 (que leí que se usaba)
2. No sé qué registro pasarle a la instrucción sw para que guarde lo que quiero en el heap

Hice este "código" para ilustrar como yo creo que debería ser, pero no estoy segura, y además para no parecer tan barsa de preguntar todo jajaja

.data
* static data *
li a7, 9
syscall
matriz_nueva: .word
.text 
...
sw ?

**Comment by tocococa** [comment]
La ecall 9, `sbrk` se utiliza para simular pedir memoria extra al SO, en el caso del emulador y del código no es necesario, ya que la simulación del loader te deja con más que suficiente espacio para memoria dinámica de lo que (espero) necesites. Puedes ver la memoria (y las distintas secciones de esta) que estás ocupando en la pestaña "Data Segment" una vez que corres el assembler.

Si quieres guardar 4 bytes en el heap, deberías ejecutar algo así como:
```
sw t1, <address_at_heap>
```
o si tienes la dirección donde estás trabajando en el heap guardada en otro registro,
```
sw t1. <offset>(t2)
```
tal como harías para guardar algo en tu sección `.data`.

**Comment by beatrizacuna** [comment]
entonces sería algo así? guardar lo que este en t1 en el heap: sw t1, 0(matriz_nueva)

**Comment by tocococa** [comment]
Emmmm, no se que quieres decir con esa instrucción, pero no va a funcionar. Dos formas de guardar algo a memoria son colocando explícitamente una dirección o label, o con la dirección cargada en un registro, que te permite ocupar un offset. Si `matriz_nueva` es la dirección de tu matriz en el heap, puedes guardar los contenidos de `t1` con `sw t1, matriz_nueva` o con las dos instrucciones `la t2, matriz_nueva` y luego `sw t1, <offset>(t2)`.

**Comment by beatrizacuna** [comment]
muchas gracias me quedó clarísimo! perdón por tanta pregunta jeje 😅
