### ISSUE TITLE
[Tarea2] Elementos en el último nivel

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2343/syllabus-2021-1#58]
Hola! Una duda, en el último nivel pueden haber nodos con el valor 1 o 0?

**Comment by tocococa** [comment]
Hola @RonaldoSosa! En el último nivel pueden haber valores 0 o 1, pero el primer valor del último nivel en aparecer en la representación no puede ser ni 0 ni 1. Si necesitas hacer algún tipo de supuesto si te encuentras con un 0, por favor déjalo mencionado en tu código.

**Comment by RonaldoSosa** [comment]
Yaaa me quedo claro, gracias :)
