### ISSUE TITLE
[Tarea 2] Output esperado

### ISSUE THREAD

**Issue by fivaldivia** [IIC2343/syllabus-2021-1#59]
Hola, como están? Quería sabe si para árboles no simétricos hay que imprimir en el output si es cuadrada o no y su determinante en caso de ser cuadrada? Que en la ayudantía donde se habló de la T2, se dijo que si no era simétrico nos olvidaramos de la matriz, por lo que asumo que imprimir "no simetrica" está correcto. Gracias!

**Comment by tocococa** [comment]
Hola @fivaldivia, en el caso de un árbol no simétrico, basta con que indiques que no es simétrico. No es necesario que revises la matriz o calcules el determinante.

**Comment by fivaldivia** [comment]
Buenísimo muchas gracias!
