### ISSUE TITLE
Duda Overflow

### ISSUE THREAD

**Issue by jalliende** [IIC2343/syllabus-2021-1#63]
Hola, estoy calculando el determinante bien el los registros de floats pero al convertirlo a integer se convierte bien si es que es representable en 32 bits, pero si no, me arroja los limites de los  representables (test 2)? Que se espera que hagamos en este caso? decir que ocurrió overflow o simplemente poner el valor que nos da la transformación?
Muchas gracias de antemano.

**Comment by tocococa** [comment]
Hola @jalliende, eso queda a criterio de ustedes mientras expliquen que hicieron en un comentario, pero yo les recomendaría avisar que ocurrió overflow y terminar con la ejecución.

**Comment by joaquineichholz** [comment]
Me queda la duda de como se evaluarán los test en la tarea, ya que el que ocurra o no overflow está directamente relacionados al método utilizado para calcular el determinante.

Por lo que para un mismo test, algunos podrían llegar al determinante y otros detener la ejecución por tener overflow.

**Comment by tocococa** [comment]
Por eso es súper importante que dejen comentado y su código sea legible (hay 0.5 puntos por eso), sabemos que la respuesta no es única y vamos intentar ver que están haciendo para llegar a cada conclusión.
