### ISSUE TITLE
[T2] Store float en memoria

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2343/syllabus-2021-1#64]
Hola 😺   Estoy intentando guardar un float en memoria de la forma fsw f4, 0(a5). Donde f4 es el registro que contiene el valor que quiero guardar (-20 en su momento), pero al hacer esta instrucción, en Data Segment se guarda -1046478848 y no sé por qué, ya que cuando hice esto mismo pero guardando ints si se guardaba el número. Hay alguna forma de arreglarlo?

**Comment by tocococa** [comment]
Hola @beatrizacuna, ese comportamiento es el esperado, ya que en el Data Segment el emulador no sabe de que dato se trata y lo interpreta todo como enteros en complemento de 2. La calidad de float o decimal o unsigned o lo que sea se la entregas tú cuando decides referenciar una cantidad de bytes e interpretarlos de cierta forme. Si revisas a mano la interpretación de -1046478848 en binario y lo reinterpretas como un float creo que debiese ser -20.0 (?). 

También te puede servir saber que en Tools>Floating Point Representation hay una herramineta que te permite monitorear los contenidos de algún registro de punto flotante durante la ejecución de tu programa.

**Comment by beatrizacuna** [comment]
Muchas gracias tienes toda la razón 😄  y está bien llamar al registro con f4 o debería ser ft4?

**Comment by tocococa** [comment]
La convención de llamada para `f4` es `ft4`, asegúrate de respetarla por favor porque si no vas a tener un descuento.
