### ISSUE TITLE
Pauta Tarea 2

### ISSUE THREAD

**Issue by francisca0308** [IIC2343/syllabus-2021-1#65]
Hola!

Me gustaría saber si hay una pauta de la tarea, más allá de los puntajes asignados en el enunciado para cada ítem. Esto en particular para saber si existe la posibilidad de obtener puntaje en la parte de programación, sin haberla completado del todo.

Muchas gracias,
Francisca

**Comment by tocococa** [comment]
Hola @francisca0308, lamentablemente no hay una pauta más allá de lo descrito en la evaluación y el único puntaje correspondiente a código son los 0.5 puntos de la sección Assembly, pero si tienes alguna dificultad particular por favor escríbenos al mail del curso o a mi correo y podemos conversar.
