### ISSUE TITLE
Tiempo de ejecución: calculo de determinante

### ISSUE THREAD

**Issue by jtcaraball** [IIC2343/syllabus-2021-1#66]
Hola!! Mi implementación del calculo de determinante es una cosa un poco monstruosa que usa stacks para pasar de recurisvidad a iteratividad que funciona pero tiende a morir antre más grande el input, ~~20 segundos~~ 50 segundos (lo cronometre :sob:) para el determinante de una matriz 6x6 es muy lento? (en python, donde testie la implementación, el mismo algoritmo lo hace instantaneo para matrices gigantes >.>)
Aiiiiuda :cry:

**Comment by tocococa** [comment]
Hola @jtcaraball, déjanos un comentario al comienzo de tu código y lo tendremos en consideración al momento de corregir, pero si entregas el resultado correcto no es necesario que entres a optimizar (aunque si fuera una aplicación real si deberías hacerlo).

**Comment by tocococa** [comment]
Hola @jtcaraball, déjalo comentado al comienzo de tu código y lo tendremos en cuenta al momento de corregir. Si entregas el resultado correcto no te preocupes por optimizar ahora (aunque si fuera una aplicación real si habría que revisar que haces que agrega tanto overhead).

**Comment by jtcaraball** [comment]
Muchas gracias por la respuesta! Solo por si alguien más tiene este problema, resetear el emulador/computador lo arreglo, pase de los 50 segundos a menos de 1 sin cambiar nada en el codigo.
Saludos!
