### ISSUE TITLE
Resultados moon.asm

### ISSUE THREAD

**Issue by robertov1** [IIC2343/syllabus-2021-1#68]
Hola!

Es normal que en moon.asm probando con las 6 combinaciones de políticas de reemplazo y asociación para un mismo input me de casi lo mismo siempre (mismo hit-rate y casi los mismos counts)? Alcanzo a hacer 4 iteraciones antes de que termine el programa.

Si hay alguna forma de que den distintos (con alguna combinación de inputs) sería de mucha ayuda!

Muchas gracias!

**Comment by tocococa** [comment]
Hola @robertov1, puedes revisar la issue #46, ahí se pregunta algo parecido.

**Comment by robertov1** [comment]
Perdón, no la había visto!

Muchas gracias!
