### ISSUE TITLE
Problema con ecalls

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2343/syllabus-2021-1#69]
Hola, estoy llamando esta ecall (EsSimetrico) y me imprime todo lo definido en data.
![image](https://user-images.githubusercontent.com/62180259/123016986-c4ca9580-d399-11eb-8b15-7d3b1cafb8d3.png)

Acá el código entra en la etiqueta simetrico y carga EsSimetrico
![image](https://user-images.githubusercontent.com/62180259/123017124-f8a5bb00-d399-11eb-804c-a64a358d713e.png)

No entiendo porque me imprime no cuadrara, cuadrada y det = n/a si no las estoy cargando

**Comment by tocococa** [comment]
Hola @dsepulveda3, tienes que terminar los strings con `\0` en lugar de `\n`. La terminación con `\n` fue un typo mio en código de ejemplo de ecalls, que ya está corregido.
