### ISSUE TITLE
Formato de la I1

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2343/syllabus-2021-1#7]
Hola! Que quería preguntar cual sería el formato de la I1.
¿Cuanto tiempo dura?
¿Tendremos todo un día para hacerla o habrá que entregarla en un formato específico?

**Comment by tocococa** [comment]
Hola! 

Van a tener desde la publicación de la prueba en la mañana hasta que se acabe el día para responder y entregar la prueba, así que no deberían tener problemas de tiempo ni de tope de horario. La prueba será de desarrollo e incluirá tanto ejercicios como respuestas teóricas, pero no se preguntará por programación en RISC-V. El formato de entrega probablemente sea texto escaneado o un documento de texto que se entregarán por SIDING.

**Comment by mjgarrido1** [comment]
Hola! solo para confirmar, la prueba será con apuntes?

**Comment by FJavierOss** [comment]
Hola, existe algún nombre especifico en el que se tenga que subir cada pregunta al cuestionario del siding? Ejemplo P1_nombreapellido.pdf ?
