### ISSUE TITLE
Problema cargando words en registros floating points

### ISSUE THREAD

**Issue by julioag** [IIC2343/syllabus-2021-1#72]
Hola, 

Estoy teniendo un problema en el cálculo del determinante cuando intento cargar una palabra en un registro float me está apareciendo un NaN, específicamente así:

`flw ft4, 0(t1) ` 
Donde la palabra viene siendo -296

Alguna forma de resolver esto? La idea es poder ir editando la matriz y guardándola de manera que necesito los floats. Me resulta cuando lo leo con un registro entero pero dado que se va editando la matriz parte del numero se pierde por el redondeo.

**Comment by tocococa** [comment]
Hola @julioag, si estás intentando cargar directamente el -296 en representación en complemento de 2, al interpretarlo como float te va a indicar NaN porque el -296 en complemento de 2 corresponde al `1111 1111 1111 1111 1111 1110 1101 1000b` y esa no es una representación correcta de un número de punto flotante. Lo que debes hacer es ocupar las instrucciones para convertir entre representaciones de punto flotante a complemento de 2 y viceversa.
