### ISSUE TITLE
[T2] fflags

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2343/syllabus-2021-1#73]
Hola! En mi tarea cuando ocurre overflow, en la sección de Control and Status, el valor de fflags cambia, al igual que el de fcsr, y quería saber si esto afecta de alguna manera a la compilación del código o a otro factor que yo no he visto al ejecutarlo. Muchas gracias!

**Comment by tocococa** [comment]
Hola @beatrizacuna, eso no afecta la ejecución de tu código, pero si quieres, podrías acceder a dichos flags para detectar overflow u otros errores que pueden ocurrir durante la operación con números de punto flotante, como cambios en el redondeo o demás.
