### ISSUE TITLE
[T2] Puntajes intermedios

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2343/syllabus-2021-1#74]
Hola! Estoy un poco mareado con el tema del determinante y no creo que lo logre calcular, entonces quería saber si iba a haber puntaje intermedio por decir que el árbol es simétrico y/o que se puede formar matriz con los elementos o si darán puntaje sólo por presentar los 3 outputs.

Gracias de antemano!

**¡¡Quejas y reclamos vía mail a `iic2343@ing.puc.cl` o a `yadran@ing.puc.cl`!!**

**Comment by tocococa** [comment]
Hola @Jamesmoreno21, son 6 tests (tal como sale en la sección de evaluación) y cada uno mide algo en particular. Lamentablemente el puntaje es binario para cada test (pasa o no), pero la van a estar repartidos de manera equitativa para cada condición o conclusión que pueda haber, por lo que no lograr calcular el determinante no debiese tener un impacto demasiado grande.

**Comment by Jamesmoreno21** [comment]
Entiendo😢 gracias por la respuesta rápida!
