### ISSUE TITLE
Giga overflow

### ISSUE THREAD

**Issue by jtcaraball** [IIC2343/syllabus-2021-1#75]
Sorry por preguntar tan cerca de la entrega pero tengo un problema titanico.. que pasa si ocurre overflow tan grande que la multiplicación de dos positivos da positivo pero porque se paso todos los negativos???  En particular el test 2 pide multiplicar 8002 * 1233000 que es un número muy pero muy grande (aprox 5 veces el tamaño del número positivo más grande que se puede en 32 bits :c)
Saludos!!

**Comment by tocococa** [comment]
Hola @jtcaraball , lo que puedes hacer para revisar ese tipo de overflow es tomar el producto, dividirlo por uno de los multiplicandos y ver si ese resultado corresponde al otro multiplicando. Lo que ocurre con RISC-V, es que la instrucción de multiplicación `mul` guarda los menores 32 bits del resultado en el resgitro indicado, mientras que la instrucción `mulh` guarda los 32 bits superiores del resultado, por lo tanto, ocurre algo como lo siguiente:
```
let a0 <- 8002, a1 <- 1233000
mul t0, a0, a1 -> t0 = 1.276.531.408d <-> 0100 1100 0001 0110 0101 0010 1101 0000b
mulh t1, a0, a1 -> t1 = 2d <-> 0000 0000 0000 0000 0000 0000 0000 0010b
```
Dado que el resultado de `8002 * 1233000` corresponde a `0000 0000 0000 0000 0000 0000 0000 0010 0100 1100 0001 0110 0101 0010 1101 0000b`.

**Comment by jtcaraball** [comment]
Muchisimas gracias!!!!
