### ISSUE TITLE
ecalls (salto de linea e impresión)

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2343/syllabus-2021-1#76]
Hola, tengo esto en el codigo
![image](https://user-images.githubusercontent.com/62180259/123170598-b4252880-d448-11eb-992b-526f2c2504a9.png)

Llamo el EsDetNA y no me lo imprime.
![image](https://user-images.githubusercontent.com/62180259/123170701-d28b2400-d448-11eb-9f3c-22f84ded36e2.png)

Tambien me gustaría saber como hacer un salto de linea para que no me imprima todo junto como sale en la foto

**Comment by tocococa** [comment]
Hola @dsepulveda3, el salto de linea se hace con `\n`. Respecto a porqué no imprime EsDetNa, no podría decirte porqué ocurre sin ver el resto de tu código, pero te aseguraste que está entrando a esa sección?

**Comment by dsepulveda3** [comment]
No me esta imprimiento el salto de linea :/
![image](https://user-images.githubusercontent.com/62180259/123174809-b8ecdb00-d44e-11eb-93e1-b1565165ad85.png)

**Comment by dsepulveda3** [comment]
Y si, si esta entrando en la instrucción
![image](https://user-images.githubusercontent.com/62180259/123175099-31ec3280-d44f-11eb-8e3b-a2b8f9e21bc0.png)

**Comment by maogaz** [comment]
@tocococa Si ocupo salto de línea me imprime todas las líneas de como dice la issue #69 y si ocupo "\0" no pasa nada, cual debo ocupar?? 

Con \n : 
![image](https://user-images.githubusercontent.com/26102280/123175041-197c1800-d44f-11eb-99af-76c598651142.png)
![image](https://user-images.githubusercontent.com/26102280/123175061-213bbc80-d44f-11eb-8fbe-b970b54b0870.png)

Con \0:

![image](https://user-images.githubusercontent.com/26102280/123175114-3add0400-d44f-11eb-8f8e-c068709f8615.png)
![image](https://user-images.githubusercontent.com/26102280/123175133-429ca880-d44f-11eb-95ac-c7e755dd0303.png)

**Comment by Jamesmoreno21** [comment]
Yo ocupe ambas para que saliera bien, tipo \n\0, por si les sirve

**Comment by tocococa** [comment]
Está bien eso @Jamesmoreno21, pero es porque hay dos ecalls que imprimen, 4 = PrintString, que necesita un string con el null terminator pero no requiere especificar el largo, y 64 = Write, que no necesita un null terminator pero sí necesita el largo del string. Creo que puede estar pasando algo de ese estilo.

**Comment by dsepulveda3** [comment]
![image](https://user-images.githubusercontent.com/62180259/123180470-551bdf80-d459-11eb-885c-285a7f97db57.png)

Me aparece este error cuando pongo el 4 :/

**Comment by tocococa** [comment]
Eso debe ser porque la dirección del string que le estás pasando en `a0` no es válida. Revisa que estés pasando bien el argumento antes de la llamada.
