### ISSUE TITLE
Horario I2

### ISSUE THREAD

**Issue by FJavierOss** [IIC2343/syllabus-2021-1#77]
Hola quisiera saber a que hora será la interrogación 2 del curso, que en mi caso particular cae el mismo día que el examen de contabilidad, por lo que quería saber si se podía salvar el tope con horarios distintos.

Gracias

**Comment by tocococa** [comment]
Hola @FJavierOss, en principio el horario y formato de la I2 va a ser el mismo que el de la I1, por lo que no debieses tener problemas con el tope de horario.

**Comment by FJavierOss** [comment]
Ya buenisimo, Gracias. Igual al final habian cambiado la fecha del examen de contabilidad y no me habida dado cuenta :sweat_smile:
