### ISSUE TITLE
Ayudantía 8 

### ISSUE THREAD

**Issue by fcartoni** [IIC2343/syllabus-2021-1#78]
Hola!! No entiendo porque en el primer ejercicio agrega 3 ciclos que se supone que son por las instrucciones NOP agregadas después del jump, si se supone que en el enunciado se había supuesto que se hacía predicción de que los jumps no ocurrían.

También tengo una pregunta del último ejercicio, no entiendo porqué se pierden 10 ciclos, no deberían ser 10 etapas a las que se les hace flush? 

Gracias :)

**Comment by AndresGonzalez5** [comment]
Error de enunciado con respecto al primer ejercicio (ups!). Se supone que no se predicen los saltos y por eso al llegar la instrucción JNE a MEM, las siguientes tres instrucciones se descartan y se suman esos 3 ciclos.

Como cada instrucción se está añadiendo en el siguiente ciclo, en el momento en que se llega a MEM (etapa 11) y se determina que hay un salto, ya habrán pasado 10 ciclos de instrucciones añadidas que deben ser descartadas (flush). Y eso sucede cada vez que hay un salto.
