### ISSUE TITLE
Horario y contenidos I2

### ISSUE THREAD

**Issue by fcartoni** [IIC2343/syllabus-2021-1#79]
Hola! A qué hora es la I2?

**Comment by raimundomartinez** [comment]
Hola! También me gustaría saber, ¿qué contenidos entran a la I2?

**Comment by lulugross** [comment]
El profesor mando un correo diciendo:

"La I2 constará de cinco preguntas, de las cuales ustedes tiene que elegir y contestar sólo 4; es decir, a cada estudiante se le va a corregir sólo 4 preguntas.

Los temas de las preguntas son los siguientes:

1) Pipelining
2) I/O
3) Memoria virtual
4) Paralelismo con memoria compartida: multiprocesadores UMA y NUMA (es decir, sólo diaps. 33 a 66 de "Arquitecturas Paralelas")
5) ISA

--Yadran"

**Comment by joaquineichholz** [comment]
@fcartoni según el programa la I2 parte a las 9:00 y según la issue #77, el formato y duración es el mismo que la I1.
