### ISSUE TITLE
Notas Tarea 2

### ISSUE THREAD

**Issue by lldavico** [IIC2343/syllabus-2021-1#80]
Hola, quería saber si las notas de la tarea 2 estarán antes de este jueves que es la I2. Más que nada para saber si vamos a tener una nota de presentación!

Gracias

**Comment by EstebanReyes1998** [comment]
Apoyo esto!
Sería muy útil para todos conocer eso antes del examen

**Comment by tocococa** [comment]
Hola, perdón por el atraso, pero las notas van a estar mañana, cuando se cumplen 15 días hábiles desde la entrega.

**Comment by folozano** [comment]
Una duda, yo siempre he escuchado que el criterio son 10 días hábiles desde la prueba, o 15 días, no 15 días hábiles. Hoy (miércoles) se van a cumplir 15 días hábiles a las 23:59, y se cumplen 21 días desde la entrega. Eso significa que se sobrepasó el criterio en sus dos formas.

**Comment by lldavico** [comment]
Aparte que cualquiera de los dos plazos es el **plazo maximo**.
