### ISSUE TITLE
Tests T2

### ISSUE THREAD

**Issue by lucas-valenzuela** [IIC2343/syllabus-2021-1#81]
Hola,

me pregunto si podrían subir los test que usaron en las tareas 2, pues tengo una duda sobre un caso que me comentaron en la corrección.

Saludos!

**Comment by tocococa** [comment]
Los tests están disponibles [acá](../../tree/master/Tareas/T2/arboles_pauta.txt).

**Comment by lucas-valenzuela** [comment]
Gracias @tocococa, voy a ver si logro subir algo en la tarea para amortiguar el 2 que me saqué en la I2!
Saludos :)

**Comment by mpbosnic** [comment]
Hola @tocococa ! Creo que en el test 5 debería decir que el árbol es simétrico.

**Comment by tocococa** [comment]
Hola @mpbosnic, está arreglado, no afecta las notas en todo caso.
