### ISSUE TITLE
Q&A I2

### ISSUE THREAD

**Issue by tocococa** [IIC2343/syllabus-2021-1#82]
# Consultas I2

Grabación: https://drive.google.com/file/d/1rMspANDHFHgaZbkGGV8H1YrBLU-yIDTh/view?usp=sharing

## Aspectos generales

Deben responder 4 de 5 preguntas, si entregan 5 respuestas, el cuerpo de ayudantes se reserva el derecho de escoger cuál pregunta no se considerará para el puntaje final :trollface:.

Hay un buzón para cada pregunta en SIDING.

## P0

Firmen a mano, idealmente entréguenla en el buzón de la P1 o en el buzón de la P2 si no respondieron la P1. El resto de la prueba puede ser a computador o a mano, mientras la letra sea clara.

## P1: Memoria Virtual

- ¿Cuando se dice que los programas tienen 2 MB de memoria disponible es entre todos los programas? **R:** No, cada programa cree que tiene 2 MB de memoria.

- ¿Podemos usar direcciones en bianrio en lugar de hexadecimal? **R:** Sí.

- ¿Asumimos que el computador es de 32 bits? **R:** 

- ¿La TLB parte vacia? **R:** Parte con contenido inválido.

- ¿Cómo es el tamaño de página en la 1, no me calza el número de bits con el tamaño de página? **R:** Deben considerar que las direcciones de la página virtual no es sólo la dirección, también incluye el offset.

- ¿A que se refieren las direcciones virtuales de 0x000 a 0xFFFF? **R:** Se refiere a que cierto componente de esa dirección es el número de página, lo demás se usa para otras cosas del direccionamiento.

- Para responder la B y C, ¿podemos hacer un supuesto respecto al tamaño de cada palabra? **R:** Se puede calcular el tamaño de cada palabra, y no necesariamente es 1 Byte.

- ¿Podemos suponer que el tamaño de una entrada ocupa una palabra completa? **R:** Las direcciones con el largo de la palabra entrega el largo total.

## P2: Pipelining

- ¿Debemos saber que hace cada FEX? **R:** No es necesario para responder la pregunta.

- ¿Asumimos entonces que el resultado lo obtenemos luego de fex3? **R:** Sí.

- ¿Un mov también se obtiene luego de fex3? **R:** Si originalmente se obtiene luego de EX regular, entonces si.

- ¿Que no tenga control de predicción de saltos es lo mismo que decir que no va a saltar? **R:** No es lo mismo.

- ¿Para FEX1, FEX2, FEX3 el resultado esta listo en FEX3 pero tiene que entrar en FEX1? **R:** Sí, entra por FEX1 y sale por FEX3.

- ¿Que hace la operacion INC B? **R:** `B = B + 1`

- ¿Cómo sé cuál de las FEX es la que ejecuta la operación? **R:** Se tiene que pasar por las 3.

- Si tenemos a cmp y jmp como instrucciones separadas, ¿Qué significaría eso para la fase EX del jmp? no se hace? **R:** En los ejemplos siempre se obviaba el CMP. Es necesario para los jmps condicionales.

- ¿Que no tenga control de prediccion de saltos significa que siempre hace la misma prediccion, o no predice? **R:** Si no tiene predicción de saltos entonces no predice.

- ¿"cuantos ciclos se perderan" se refiere a cuantos ciclos ya no se haran dado que hay predicción? **R:** Se refiere a cuántos ciclos se van a desperdiciar.

- ¿Cómo se relaciona la comparación con el salto condiciona? **R:** Las comparaciones se traducen en un resultado que queda un un flag, que quedan almacenados en el registro status. El salto revisa el registro de status y salta o no respecto a esto.

- ¿Debemos nosotros insertar instrucciones NOP para evitar hazards? **R:** Sí, deben poner las instrucciones NOP.

- ¿El FADD A, B almacena la suma en A? **R:** Funciona equivalente a la instrucción ADD A, B.

- ¿Los saltos incondicionales igual saltan después de MEM o no? porque tienen que procesar el label? **R:** Sí.

## 3: Paralelismo con memoria compratida

- ¿Que es `X++`? **R:** `X++` es equivalente a `X=X+1`.

- ¿Dado que los datos no estan en cache en un inicio, se puede traer mas de 1 dato a la cache (ej. arr(0) y arr(1) en un mismo ciclo o hay que hacerlo por separado? **R:** Pueden suponer que el dato se carga/actualiza a la caché sin perder ticks, ocurre a la vez que se ejecuta la instrucción.

- ¿Para la B la idea es agregar otra letra al protocolo MESI que me permita hacer alguna optimización? **R:** Si, esa es la idea.

## 4: I/O

- Cuando se dice "describe cómo implementarías ya sea el espacio de puertos de I/O o el mapa de memoria, según corresponda" ¿La idea es describir solo el que yo elegí como el mejor? o ambos? **R:** La que tu elijas.

- ¿A que se refiere con definir el formato de comandos? **R:** Las instrucciones que la CPU envía al dispositivo.

- ¿Se puede asumir que se le puede indicar al dispositivo que se comunique sólo cuando ocurre algo en particular? **R:** No, el dispositivo está constantemente comunicándose con la CPU a través de interrupciones.

- ¿A que se refieren con psuedocódigo? **R:** Pseudo-assembly.

## P5: ISA
- A qué se refiere con instrucciones "extra'? **R:** Quiere decir instrucciones que son necesarias porque el valor almacenado en un registro va a ser sobrescrito.

- ¿A que se refiere que se destruyen los operandos? **R:** Durante la operación, el valor que está en un operando es cambiado por otro valor.

- A qué se refiere con instrucciones "extra'? **R:** Quiere decir instrucciones que son necesarias porque el valor almacenado en un registro va a ser sobrescrito.

- ¿Se tiene que escribir todo el código en la A y B, o puede ser la instrucción en sí? **R:** Las instrucciones que se piden.

- ¿Cuántos registros hay? **R:** Si tienes 6 bits para referenciar registros, ¿cuántos registros hay?

**Comment by MINGOD24** [comment]
En la pregunta 3, debemos seguir el orden de instrucciones que esta en el enunciado, o debemos buscar el orden correcto?

**Comment by tocococa** [comment]
@MINGOD24, el orden de las instrucciones es el que sale en la pregunta.

**Comment by ncasassus** [comment]
Hola! En la P1: Memoria virtual cuando preguntan por "¿Asumimos que el computador es de 32 bits? R:" la respuesta está vacía. Se puede saber cuál era la respuesta?

**Comment by tocococa** [comment]
@ncasassus, la anoté pero no se respondió en la sesión, la respuesta es sí, pueden asumirlo mientras lo indiquen en su respuesta.

**Comment by ncasassus** [comment]
@tocococa graciaas!

**Comment by MINGOD24** [comment]
Hola, se puede subir un excel para la pregunta 2?

**Comment by jcechavarri** [comment]
Hola!
No me queda clara la respuesta de

> Si tenemos a cmp y jmp como instrucciones separadas, ¿Qué significaría eso para la fase EX del jmp? no se hace? R: En los ejemplos siempre se obviaba el CMP. Es necesario para los jmps condicionales.

Significa que debemos considerar ambas instrucciones como separadas?

**Comment by tocococa** [comment]
@MINGOD24 Tienes que subir un solo archivo por respuesta, puedes subir un pdf con un pantallazo del Excel y tu respuesta a la parte b).

@jcechavarri Si.

**Comment by Aloncarrasco** [comment]
Para la pregunta 1 asumo que la ram parte vacia? y lo otro, asumo que no hay páginas que comparten el mismo frame?

**Comment by diegovaras97** [comment]
Hola, se puede entregar un archivo comprimido (.rar) con un pdf y un excel en la pregunta 2?, no logro convertir mi archivo excel en un pdf decente.

**Comment by raimundomartinez** [comment]
Hola. En la pregunta 5 sale "usando instrucciones aritméticas tipo 80x86 (IA-32) de dos operandos".
¿Esto significa que puedo usar instrucciones genéricas de dos operandos, (ej: load r1, a) o significa que debo usar las instrucciones IA-32 (ej: ADD EAX, #6765)?
De ser el segundo caso, ¿donde puedo ver el listado de instrucciones IA-32? Que en las slides solo salen un par de ejemplos muy específicos.

**Comment by Aloncarrasco** [comment]
porfaa más plazo

**Comment by Tvergara** [comment]
Para la pregunta 5 se puede suponer que cada registro es de 64 bits?

**Comment by fddelabarra** [comment]
> porfaa más plazo

si, por favor :(

**Comment by RonaldoSosa** [comment]
> porfaa más plazo

siii, por favor :´´(

**Comment by tocococa** [comment]
@Alonsocarrasco Si, puedes asumir que la RAM parte vacía en la P1.

@diegovaras97 Si entregas un archivo comprimido por favor que sea un zip, no rar.

@raimundomartinez Con instrucciones tipo 80x86 se refiere a que son del tipo `INST A, B` en lugar de `INST A, B, C` como son en RISC-V.

@Tvergara sí, siempre y cuando justifiques el supuesto.

**Comment by Pdesolmi** [comment]
> porfaa más plazo

PORFAVOOOOR

**Comment by tatanpoker09** [comment]
> porfaa más plazo
Sii por favor in yadran we trust
![image](https://user-images.githubusercontent.com/6262015/125836576-9447fdf1-6931-436a-b212-f8cfe8683048.png)

**Comment by jearaneda** [comment]
pls

**Comment by Luckbox314** [comment]
Tengo un problema, no encuentro la issue en la que dieron más plazo 😧 (sarcasm)

**Comment by tocococa** [comment]
Respecto al plazo, le escribí al profesor comentándole la situación y queda esperar a que responda, el cuerpo de ayudantes no tiene autoridad para mover el plazo sin permiso <(＿　＿)>

**Comment by tocococa** [comment]
Tienen 45 minutos extra, hasta las 15:45, para entregar.

**Comment by Araos827** [comment]
Holaaaa a quien tengo que hablarle si es que se me cerro el buzon :(?
