### ISSUE TITLE
I1-2016-1 P2.c)

### ISSUE THREAD

**Issue by cchauriye** [IIC2343/syllabus-2021-1#9]
Hola! En la I1-2016-1, pregunta 2.c) usan un "reverse counter". ¿Debiésemos entender cómo funciona eso? ¿podemos usarlo eventualmente? Gracias!

![Captura de Pantalla 2021-04-21 a la(s) 13 01 02](https://user-images.githubusercontent.com/31393605/115592868-ca283880-a2a1-11eb-8fe4-87b64bd4ebc1.png)

**Comment by tocococa** [comment]
Hola!

No es necesario que entiendan _cómo_ funciona, si no más bien _que_  hace. Si en alguna pregunta de la prueba les aparece un componente que no han visto, tendrán la debida explicación de para que sirve y que hace, si quieren usar un componente que no se ha visto en clases, ahí si tendrían que explicar cómo funciona, para asegurarte que es posible construirlo.
